#!/usr/bin/env python3
"""The OUI vendor-lookup DERIVE engine (discovery-inbox corpus Rung 3) — the IEEE MA-L/MA-M/MA-S registries reduced
to a pinned prefix->vendor lookup, so the discovery inbox can annotate a candidate's MAC with its manufacturer (a
recognition aid for the human class-pick; a DISPLAY HINT, never a class guess — SECURITY C18 F8). no-bespoke: the
WHOLE public registry is derived + pinned + `--check`'d, never a hand-curated subset (which would rot).

Three modes, with the BRICK-1 offline/network split (no network in an install-gating path):
  * --check  (VALIDATE, DEFAULT-safe): OFFLINE coherence gate — schema:1, a non-empty prefixes dict, every key is
    6/7/9 lowercase-hex nibbles, len(prefixes)==lock.prefix_count (the honest-count invariant — a number kept honest
    by a check, per CLAUDE.md), sha256(json)==lock.content_sha256 (the tamper floor), lock.sources == the EXACT 3
    IEEE URLs. Makes NO network call. Runs in tests/validate beside gen-dashboard-floor --check / gen-image-digests
    --check.
  * --refresh  (OPERATOR/CONTROL-VM, NETWORK): GET the 3 IEEE CSVs, reduce to prefix->vendor (addresses DROPPED),
    write oui/oui-lookup.generated.json + oui/oui-lookup.lock.yml. NEVER run in CI/deploy (a validate static gate
    pins that). The reviewable `git diff` on the .json IS the churn (mirrors gen-image-digests.py --refresh).
  * --list  (OFFLINE): print the pin summary (row count + a few examples).

Longest-prefix-match is the READER's job (service/discovery._vendor_for probes 9->7->6 nibbles): IEEE re-parcels a
/24 into /28 (MA-M) and /36 (MA-S) blocks, so a naive first-3-bytes lookup ships the WRONG vendor for a small-block
device. This generator stores each assignment at its OWN length so a single flat dict serves all three registries.

Usage:  python3 scripts/gen-oui.py [--check | --refresh | --list]
"""
import csv
import datetime
import hashlib
import io
import json
import os
import re
import sys
import urllib.error
import urllib.request

import yaml

from kontroll import paths

OUI_DIR = paths.OUI_DIR
LOOKUP = os.path.join(OUI_DIR, "oui-lookup.generated.json")
LOCK = os.path.join(OUI_DIR, "oui-lookup.lock.yml")
# (url, nibble-length) — the three IEEE MA registries. The `Assignment` column is the hex prefix: MA-L=6, MA-M=7,
# MA-S=9 nibbles. Order is STABLE (the lock's `sources` list is asserted against these EXACT URLs by --check).
SOURCES = (
    ("https://standards-oui.ieee.org/oui/oui.csv", 6),      # MA-L (/24) — the classic OUI
    ("https://standards-oui.ieee.org/oui28/mam.csv", 7),    # MA-M (/28)
    ("https://standards-oui.ieee.org/oui36/oui36.csv", 9),  # MA-S (/36, "OUI-36")
)
FETCH_TIMEOUT = 30           # s; a slow/unreachable registry raises -> --refresh aborts (never a partial pin)
_KEY_RE = re.compile(r"^([0-9a-f]{6}|[0-9a-f]{7}|[0-9a-f]{9})$")   # exactly 6, 7, or 9 lowercase-hex nibbles
_SHA256 = re.compile(r"^sha256:[0-9a-f]{64}$")
_VENDOR_CAP = 64


def _clean_vendor(name):
    """A registrant org name reduced to a compact display string: collapse internal whitespace, strip a trailing
    '.', cap at _VENDOR_CAP chars (a runaway registrant name can't bloat a row / a GUI cell). Empty stays '' (some
    IEEE rows are 'Private'/blank — a real value, not a drop reason)."""
    return " ".join((name or "").split()).rstrip(".")[:_VENDOR_CAP]


def _sha256_bytes(b):
    return "sha256:" + hashlib.sha256(b).hexdigest()


def _lookup_bytes(prefixes):
    """The committed lookup bytes — json.dumps(sort_keys, indent=1) + a trailing LF, so the lock's content_sha256
    matches the on-disk file byte-for-byte and --check's hash compares cleanly (the gen-dashboard-floor _board_bytes
    discipline). indent=1 keeps ONE prefix per line = a reviewable `git diff`, not a single opaque line."""
    return (json.dumps({"prefixes": prefixes, "schema": 1}, sort_keys=True, indent=1) + "\n").encode("utf-8")


def render_lock(prefixes, sha, generated_at):
    """Byte-exact lock content — hand-written (like gen-dashboard-floor.render_lock) so it stays yamllint-clean +
    diff-minimal across re-refreshes. `generated_at` is provenance ONLY (NOT read by --check — determinism)."""
    return ("---\n"
            "# GENERATED by scripts/gen-oui.py --refresh — DO NOT hand-edit. The OUI vendor-lookup pin: the IEEE\n"
            "# MA-L/MA-M/MA-S registries reduced to prefix->vendor (registrant addresses DROPPED), frozen so\n"
            "# gen-oui.py --check validates it OFFLINE (BRICK-1). Re-derive with --refresh (network, operator-run);\n"
            "# the diff on oui-lookup.generated.json is the reviewable churn. Display-only (SECURITY C18 F8).\n"
            "schema: 1\n"
            "sources:\n"
            + "".join('  - "%s"\n' % url for url, _ in SOURCES)
            + "content_sha256: \"%s\"\n" % sha
            + "prefix_count: %d\n" % len(prefixes)
            + "generated_at: \"%s\"\n" % generated_at)


# --- the pinned artifacts (OFFLINE loaders) ------------------------------------------------------------------

def _load_lock():
    try:
        with open(LOCK, encoding="utf-8") as fh:
            return yaml.safe_load(fh) or {}
    except (OSError, yaml.YAMLError):
        return {}


def _load_lookup():
    """(raw_bytes, parsed_dict) of the committed lookup (raises OSError/ValueError to the caller if absent/malformed)."""
    with open(LOOKUP, "rb") as fh:
        raw = fh.read()
    return raw, json.loads(raw.decode("utf-8"))


# --- --refresh (NETWORK, operator/CI-authoring only) ----------------------------------------------------------

def _fetch_csv(url):
    """GET one IEEE CSV (NETWORK) -> its text. The ONLY network call, --refresh only. A slow/unreachable registry
    RAISES (the caller aborts the whole refresh — never a partial pin)."""
    req = urllib.request.Request(url, headers={"User-Agent": "kontroll-gen-oui"})
    with urllib.request.urlopen(req, timeout=FETCH_TIMEOUT) as resp:
        return resp.read().decode("utf-8", "replace")


def _parse_csv(text, nibbles):
    """One IEEE CSV text -> {prefix: vendor} for the rows whose `Assignment` is EXACTLY `nibbles` lowercase-hex (a
    malformed/wrong-length assignment is skipped so --check's key-length invariant holds). CSV columns are
    Registry,Assignment,Organization Name,Organization Address — we take Assignment + Organization Name and DROP the
    address entirely (bloat + churn magnet + irrelevant to a vendor hint)."""
    out = {}
    for row in csv.DictReader(io.StringIO(text)):
        prefix = (row.get("Assignment") or "").strip().lower()
        if len(prefix) == nibbles and all(c in "0123456789abcdef" for c in prefix):
            out[prefix] = _clean_vendor(row.get("Organization Name"))
    return out


def refresh():
    """--refresh: GET the 3 IEEE CSVs, reduce to a single flat prefix->vendor dict, write the lookup + lock. A fetch
    failure aborts with NO file written (never a partial pin). Returns 0/1."""
    os.makedirs(OUI_DIR, exist_ok=True)
    prefixes = {}
    for url, nibbles in SOURCES:
        try:
            text = _fetch_csv(url)
        except (urllib.error.URLError, OSError, ValueError) as exc:
            sys.stderr.write("refresh: FAILED to fetch %s (%s) -- no file written (never a partial pin)\n"
                             % (url, exc))
            return 1
        got = _parse_csv(text, nibbles)
        prefixes.update(got)
        print("fetched %s -> %d rows (%d-nibble)" % (url, len(got), nibbles))
    data = _lookup_bytes(prefixes)
    sha = _sha256_bytes(data)
    prev = _load_lock()
    generated_at = (prev.get("generated_at") if prev.get("content_sha256") == sha and prev.get("generated_at")
                    else datetime.date.today().isoformat())   # no-churn on no-change (the gen-dashboard-floor trick)
    with open(LOOKUP, "wb") as fh:
        fh.write(data)
    with open(LOCK, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render_lock(prefixes, sha, generated_at))
    print("wrote oui/oui-lookup.generated.json (%d prefixes, %s)" % (len(prefixes), sha[:19]))
    return 0


# --- --check (OFFLINE — the staleness/coherence gate; BRICK-1) ------------------------------------------------

def check():
    """OFFLINE (BRICK-1) coherence: the lookup parses (schema 1, non-empty prefixes, every key 6/7/9 hex), the lock's
    prefix_count + content_sha256 + sources all agree with the committed .json. Makes NO network call. -> [problems]."""
    if not os.path.exists(LOOKUP):
        return ["oui-lookup.generated.json is missing (run gen-oui.py --refresh)"]
    try:
        raw, doc = _load_lookup()
    except (OSError, ValueError) as exc:
        return ["oui-lookup.generated.json does not parse (%s)" % exc]
    problems = []
    if doc.get("schema") != 1:
        problems.append("schema must be 1")
    prefixes = doc.get("prefixes")
    if not isinstance(prefixes, dict) or not prefixes:
        return problems + ["prefixes must be a non-empty object"]
    bad = sorted(k for k in prefixes if not (isinstance(k, str) and _KEY_RE.match(k)))
    if bad:
        problems.append("%d key(s) are not 6/7/9 lowercase-hex nibbles (e.g. %r)" % (len(bad), bad[0]))
    lock = _load_lock()
    if lock.get("schema") != 1:
        problems.append("lock schema must be 1")
    if lock.get("prefix_count") != len(prefixes):
        problems.append("lock prefix_count %r != actual %d (re-run --refresh)"
                        % (lock.get("prefix_count"), len(prefixes)))
    sha = lock.get("content_sha256")
    if not (isinstance(sha, str) and _SHA256.match(sha)):
        problems.append("lock content_sha256 %r is not a sha256:<64hex>" % sha)
    elif sha != _sha256_bytes(raw):
        problems.append("lock content_sha256 %s != sha256(oui-lookup.generated.json) %s (tampered/stale -- re-run "
                        "--refresh)" % (sha, _sha256_bytes(raw)))
    if list(lock.get("sources") or []) != [url for url, _ in SOURCES]:
        problems.append("lock sources != the expected 3 IEEE URLs (a source change without a re-refresh)")
    return problems


def _list():
    try:
        _, doc = _load_lookup()
    except (OSError, ValueError) as exc:
        sys.stderr.write("gen-oui: %s\n" % exc)
        return 1
    prefixes = doc.get("prefixes") or {}
    print("gen-oui: %d OUI prefixes pinned (%s)" % (len(prefixes), (_load_lock().get("content_sha256") or "?")[:19]))
    for k in sorted(prefixes)[:5]:
        print("  %-9s %s" % (k, prefixes[k]))
    return 0


def main(argv):
    if "--refresh" in argv:
        return refresh()
    if "--list" in argv:
        return _list()
    # default + --check: the OFFLINE coherence gate (safe bare invocation — never touches the network).
    problems = check()
    if problems:
        for prob in problems:
            sys.stderr.write("gen-oui: %s\n" % prob)
        return 1
    print("gen-oui: %d OUI prefixes coherent (--check)" % len(_load_lookup()[1].get("prefixes") or {}))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
