#!/usr/bin/env python3
"""Generate observability config (Prometheus scrape targets now; Homepage widgets next) from the enabled
device modules + the inventory — the metrics/widget analogue of gen-requirements.py.

Each device class declares its observability shape AS DATA in modules/<key>/module.yml by referencing a
telemetry METHOD by name (the registry, telemetry/<name>.yml):

    metrics:                    # a list — a class may have several sources
      - {method: host_node}     # host-agent: the host runs node_exporter (target = <host>:<port>)
      - {method: pve}           # proxy-exporter: a control-node exporter queries the device API

This generator loads the telemetry-method registry (catalog.load_telemetry), then JOINS enabled modules
(instance/fleet.yml) x their metrics entries x the inventory hosts in each module's inventory_group, and
writes prometheus/targets/<job>/<key>.generated.yml — one target per host, NEVER hand-written. The METHOD
supplies the job/port/target-shape/labels: a host-agent method renders <ansible_host>:<port>; a
proxy-exporter method renders the device address (the prometheus job's relabel_configs proxy it onto the
control-node exporter, e.g. pve-exporter:9221?target=<device>). Adding a new ingestion protocol is a
telemetry/<name>.yml drop-in — NOT an edit to this generator (node_exporter is one descriptor row, not a
hardcoded branch). Fail-closed: an unknown/missing method or a legacy {via,port} entry exits non-zero.

Standalone except for kontroll.catalog (the registry loader; no ansible) so CI + deploy-stack can run it —
running `python3 scripts/gen-observability.py` puts scripts/ on sys.path so `from kontroll import catalog`
resolves. Mirrors gen-requirements.py; the output is a GENERATED lockfile kept honest by `--check` (a
tests/validate step) — change a module's `metrics:` block, a telemetry method, or the inventory and re-run
(deploy-stack regenerates it before bringing Prometheus up).

Usage:  python3 scripts/gen-observability.py [--check | --example]   # bare = write live targets from the instance
        # overlay; --example = (re)write the committed PUBLIC lockfile from instance.example/; --check = validate it (F3)
"""
import glob
import os
import sys

import yaml

from kontroll import catalog, inventory, paths   # registries + merged-inventory (drop-ins) + overlay resolver

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = ("# GENERATED by scripts/gen-observability.py from instance/fleet.yml + modules/<key>/module.yml\n"
          "# + instance/inventory/hosts.yml. Do NOT edit by hand — change a module's `metrics:` block or the\n"
          "# inventory and re-run (deploy-stack regenerates it before bringing Prometheus up).\n")


def _load(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def _hosts_in_group(inv, group):
    """{hostname: ansible_host} for a leaf inventory group (all.children.<group>.hosts)."""
    node = ((inv.get("all") or {}).get("children") or {}).get(group) or {}
    return {name: (h or {}).get("ansible_host")
            for name, h in (node.get("hosts") or {}).items() if (h or {}).get("ansible_host")}


def _entries(method, key, group, hosts, met):
    """The (targets, labels) rows for one metrics entry, rendered per its resolved telemetry method.
    target_shape host_port (host-agent): target = <ansible_host>:<port> (the host exposes the exporter).
    target_shape device (proxy-exporter): target = <ansible_host> (the device addr; the job relabel proxies
    it onto the control-node exporter). Labels come from the method's `labels` keys, in declared order, so
    the rendered bytes match the legacy via:host {group,host} / via:proxy {host} output exactly. (`met`, the
    module's metrics entry, is carried for per-class params used by later phases.)"""
    shape = method.get("target_shape")
    if shape == "host_port" and not method.get("port"):
        sys.exit("gen-observability: telemetry method %r (used by %s) is target_shape host_port but has no port"
                 % (method.get("name"), key))
    # Resolve per-class params against the method's CLOSED allow-list (the config-injection guard): a value
    # not in `allowed` is REJECTED here, never interpolated into a target. An allowed value becomes a label
    # (label_as) — e.g. snmp `module: if_mib` -> `__param_module: if_mib`, which Prometheus passes as ?module=.
    param_labels = {}
    given = met.get("params") or {}
    for pname, pspec in (method.get("params") or {}).items():
        val = given.get(pname)
        if val is None:
            if pspec.get("required"):
                sys.exit("gen-observability: %s uses method %r which requires param %r"
                         % (key, method.get("name"), pname))
            continue
        if val not in (pspec.get("allowed") or []):
            sys.exit("gen-observability: %s param %s=%r is not in the allow-list %r for method %r "
                     "(rejected — never interpolated)"
                     % (key, pname, val, pspec.get("allowed"), method.get("name")))
        if pspec.get("label_as"):
            param_labels[pspec["label_as"]] = val
    rows = []
    for name, ip in sorted(hosts.items()):
        if shape == "device":
            target = ip
        elif shape == "host_port":
            target = "%s:%s" % (ip, method["port"])
        else:
            sys.exit("gen-observability: telemetry method %r (used by %s) has unknown target_shape %r"
                     % (method.get("name"), key, shape))
        labels = {}
        for lk in method.get("labels") or []:
            if lk == "group":
                labels["group"] = group
            elif lk == "host":
                labels["host"] = name
            else:
                sys.exit("gen-observability: telemetry method %r emits unknown label %r"
                         % (method.get("name"), lk))
        labels.update(param_labels)          # validated param labels (e.g. __param_module: if_mib)
        labels.update(method.get("static_labels") or {})   # method-level labels (e.g. __param_auth: v3_kontroll)
        rows.append(([target], labels))
    return rows


def _render(entries):
    """Hand-render the file_sd YAML (matches the existing target style; yamllint-clean)."""
    lines = [HEADER.rstrip("\n")]
    for targets, labels in entries:
        lines.append("- targets: [%s]" % ", ".join('"%s"' % t for t in targets))
        lines.append("  labels:")
        for k, v in labels.items():
            lines.append("    %s: %s" % (k, v))
    return "\n".join(lines) + "\n"


def metrics_files(fleet, inv, methods=None):
    """-> {repo_rel_path: rendered_body} for every enabled module's metrics entries. Each entry references a
    telemetry method by name (`- {method: <name>}`); the method (telemetry/<name>.yml, loaded once) supplies
    the job, target shape, port and labels. Fail-closed: a missing/unknown method, an unsupported kind, or a
    legacy {via,port} entry exits non-zero (never a silent/empty target). One file per (method job, key)."""
    if methods is None:
        methods = {m["name"]: m for m in catalog.load_telemetry()}
    out = {}
    for key in fleet.get("enabled_modules") or []:
        mp = "modules/%s/module.yml" % key
        if not os.path.exists(os.path.join(ROOT, mp)):
            continue
        module = _load(mp)
        group = module.get("inventory_group")
        hosts = _hosts_in_group(inv, group)
        seen = set()                                       # (job,key) uniqueness is PER-MODULE: two different
        for met in (module.get("metrics") or []):          # classes legitimately share targets/<job>/
            name = met.get("method")
            if not name:
                sys.exit("gen-observability: %s has a metrics entry with no 'method' "
                         "(legacy {via,port}? migrate it to {method: <name>})" % key)
            method = methods.get(name)
            if method is None:
                sys.exit("gen-observability: %s references unknown telemetry method %r (add telemetry/%s.yml)"
                         % (key, name, name))
            if method.get("kind") not in ("host-agent", "proxy-exporter"):
                sys.exit("gen-observability: telemetry method %r has unsupported kind %r "
                         "(host-agent | proxy-exporter)" % (name, method.get("kind")))
            path = "prometheus/targets/%s/%s.generated.yml" % (method["job"], key)
            if path in seen:
                sys.exit("gen-observability: %s declares two metrics entries resolving to job %r (%s) — "
                         "a class may not declare two methods sharing a job" % (key, method["job"], path))
            seen.add(path)
            entries = _entries(method, key, group, hosts, met)
            if entries:
                out[path] = _render(entries)
    return out


def main(argv):
    # The committed *.generated.yml are the PUBLIC, example-derived reference (F3): `--check` VALIDATES them and
    # `--example` REGENERATES them from instance.example/ (TEST-NET addrs only — no real topology in the shipped
    # tree, which make-bundle does NOT strip). The bare write (deploy-stack, live) reads the instance OVERLAY via
    # paths.resolve, so a running node regenerates its REAL targets locally — instance state, never committed to
    # origin. (After a module `metrics:` edit, re-run `--example` to refresh the committed lockfile.)
    if "--check" in argv or "--example" in argv:
        fleet = _load("instance.example/fleet.yml")
        inv = inventory.merged_inventory("instance.example/inventory/hosts.yml")
    else:
        fleet = _load(paths.resolve("config/fleet.yml"))
        inv = inventory.merged_inventory(paths.resolve("ansible/inventory/hosts.yml"))
    # normpath both sides so the set math holds on Windows too (glob returns native separators).
    want = {os.path.normpath(os.path.join(ROOT, rel)): body
            for rel, body in metrics_files(fleet, inv).items()}
    have = {os.path.normpath(p)
            for p in glob.glob(os.path.join(ROOT, "prometheus", "targets", "*", "*.generated.yml"))}

    if "--check" in argv:
        stale = []
        for path, body in want.items():
            cur = open(path, encoding="utf-8").read() if os.path.exists(path) else None
            if cur != body:
                stale.append(os.path.relpath(path, ROOT))
        for path in have - set(want):            # generated files no enabled module produces anymore
            stale.append(os.path.relpath(path, ROOT) + " (orphaned)")
        if stale:
            print("STALE observability targets — re-run scripts/gen-observability.py --example:\n  " + "\n  ".join(stale))
            return 1
        print("observability targets up to date (%d file(s))" % len(want))
        return 0

    for path in have - set(want):                # prune orphans first (a removed module/host)
        os.remove(path)
    for path, body in want.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:   # LF on every platform (stable lockfile)
            fh.write(body)
    print("wrote %d target file(s): %s"
          % (len(want), ", ".join(sorted(os.path.relpath(p, ROOT) for p in want))))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
