#!/usr/bin/env python3
"""Generate the Homepage portal's **Fleet** tile group from the enabled device modules + the inventory — the
portal-tile analogue of gen-observability.py (scrape targets) and gen-logging.py (Vector drop-ins).

The `:3000` portal (gethomepage) only READS YAML — it has no write API — and its tiles live in the operator-owned
overlay `instance/dashboards/homepage/services.yaml`. So unlike the other generators (which own a whole
`*.generated.yml` file), this one owns only a MARKED SPAN inside that hand-authored file: everything between

    # >>> kontroll fleet (generated by scripts/gen-homepage.py — do NOT edit between markers) >>>
    ...
    # <<< kontroll fleet (generated) <<<

The operator's control-plane tiles outside the markers are preserved byte-for-byte; the span between them is OURS
(the #124 banner-keyed ownership idea applied to tiles). The boundary is defined ONCE in
`kontroll.service.homepage` (`FLEET_BEGIN`/`FLEET_END` + `_split_services` + `splice_fleet_block`) — the SAME
module the `:8443` GUI Homepage editor consumes, so the generator (producer) and the editor (consumer) cannot
drift on what "the fleet span" is. The editor flags the generated section read-only and refuses to edit its tiles;
this generator is the missing producer that fills it.

JOIN: enabled modules (`fleet.yml enabled_modules`) x each module's `inventory_group` x the inventory hosts in
that group — the SAME modules x inventory join gen-observability fans over (`_hosts_in_group`, keyed on the one
dispatch seam `module.inventory_group`). One tile PER onboarded host that has a management address:

    - <inventory_group> · <host>:        # e.g. "core_switch · my-switch" (group disambiguates duplicate names)
        href: <scheme>://<ansible_host>  # a links-convenience to the device's own UI; https by default
        description: <module key>        # the device class (cisco_ios, fortigate, …)

`href:` + `description:` ONLY — NEVER a `widget:`/secret (the board is unauthenticated; C11/SECURITY.md). A class
may self-describe a tile via an OPTIONAL `homepage: {scheme, port, icon}` block in its `module.yml` (fanned like
`metrics:`); absent, the tile derives `https://<addr>` with no icon — so no module churn is required.

The committed PUBLIC reference (`instance.example/dashboards/homepage/services.yaml`, which SHIPS — make-bundle
strips only `instance/`) is regenerated from `instance.example/` (TEST-NET `192.0.2.x` only) by `--example`, and
`--check` validates it (the F3 example-driven gate). The BARE write (deploy-stack, live) splices into the private
`instance/` overlay from the live inventory — a running node regenerates its REAL fleet tiles locally, stripped
from the bundle, never committed to origin. Fail-closed: a tile value carrying a newline or a secret marker exits
non-zero (never interpolated into the unauthenticated board).

Usage:  python3 scripts/gen-homepage.py [--check | --example]   # bare = splice live instance/ overlay; --example
        # = (re)write the committed PUBLIC example span from instance.example/; --check = validate it (F3)
"""
import os
import sys

import yaml

from kontroll import inventory, paths            # merged-inventory (drop-ins) + instance-overlay resolver
from kontroll.service import homepage            # the marker constants + _split_services + splice_fleet_block (one seam)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# The full marker forms (the GUI tokenizer prefix-matches homepage.FLEET_BEGIN/END, so the descriptive tails are
# tolerated — and they tell a human reading the YAML exactly which generator owns the span and not to edit it).
FLEET_BEGIN_LINE = "# >>> kontroll fleet (generated by scripts/gen-homepage.py — do NOT edit between markers) >>>"
FLEET_END_LINE = "# <<< kontroll fleet (generated) <<<"
_EMPTY_NOTE = "# (no onboarded devices with a management address yet)"


def _load(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def _read_text(path):
    """The current services.yaml text, or '' if absent (a fresh node seeds it from instance.example/ first)."""
    try:
        with open(path, encoding="utf-8") as fh:
            return fh.read()
    except OSError:
        return ""


def _hosts_in_group(inv, group):
    """{hostname: ansible_host} for a leaf inventory group (all.children.<group>.hosts) — hosts WITHOUT an
    ansible_host are dropped (a tile with no address is dead). Identical to gen-observability._hosts_in_group so
    the two generators see the SAME hosts for a class."""
    node = ((inv.get("all") or {}).get("children") or {}).get(group) or {}
    return {name: (h or {}).get("ansible_host")
            for name, h in (node.get("hosts") or {}).items() if (h or {}).get("ansible_host")}


def fleet_rows(fleet, inv):
    """-> [{group, key, host, addr, name, href, description, icon}] one row per inventory host in an enabled
    module's group that has a management address, sorted (group, host) for a stable lockfile. The modules x
    inventory JOIN, keyed on `module.inventory_group` (the one dispatch seam). An optional `homepage:` block in
    the module supplies a non-default scheme/port/icon (fanned like `metrics:`); absent -> https/no-port/no-icon."""
    rows = []
    for key in fleet.get("enabled_modules") or []:
        mp = "modules/%s/module.yml" % key
        if not os.path.exists(os.path.join(ROOT, mp)):
            continue
        module = _load(mp)
        group = module.get("inventory_group")
        if not group:
            continue
        hp = module.get("homepage") or {}
        scheme = hp.get("scheme") or "https"
        port = hp.get("port")
        icon = hp.get("icon")
        for host, addr in sorted(_hosts_in_group(inv, group).items()):
            href = "%s://%s%s" % (scheme, addr, (":%s" % port if port else ""))
            rows.append({"group": group, "key": key, "host": host, "addr": addr,
                         "name": "%s · %s" % (group, host),   # "<group> · <host>" — unique per tile
                         "href": href, "description": key, "icon": icon})
    rows.sort(key=lambda r: (r["group"], r["host"]))
    return rows


def _assert_safe(rows):
    """Fail-closed config-injection guard (the gen-observability allow-list analogue): no tile field may carry a
    newline (would smuggle extra YAML lines into the unauthenticated board) or a secret/widget marker (C11). A
    crafted inventory `ansible_host` can't break out of its tile."""
    for r in rows:
        for field in ("name", "href", "description", "icon"):
            val = r.get(field)
            if val is None:
                continue
            if not isinstance(val, str):
                sys.exit("gen-homepage: tile %r field %s is not a string (%r)" % (r["name"], field, val))
            if "\n" in val or "\r" in val:
                sys.exit("gen-homepage: tile %r field %s contains a newline (injection?) — refused" % (r["name"], field))
            if "{{HOMEPAGE_VAR_" in val or "password" in val.lower():
                sys.exit("gen-homepage: tile %r field %s carries a secret marker — the fleet block is href+"
                         "description only (C11)" % (r["name"], field))


def _q(s):
    """A YAML double-quoted scalar (escapes `\\` and `"`). Emitting EVERY operator-data field quoted means a typo'd
    inventory `ansible_host` carrying a `: ` or ` #` (a YAML mapping/comment metacharacter) renders as a structurally
    valid scalar — a dead tile, never a corrupted services.yaml / blank :3000 board (adversarial review #55 finding
    #3; mirrors gen-observability quoting its scrape targets). A newline/secret is still refused upstream by
    `_assert_safe` — quoting is the structural guard, `_assert_safe` the semantic one."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_fleet_block(rows):
    """The marker-delimited fleet span text (begins with FLEET_BEGIN, ends with FLEET_END + a trailing newline).
    A `- Fleet:` gethomepage group of href+description tiles (every operator-data scalar double-quoted, see `_q`),
    or — when no host has an address — the markers around a single comment, so the span (and the editor's awareness
    of it) persists with zero tiles. The `- Fleet:` group header is emitted unquoted so `_fleet_group_names` still
    flags the section generated:true."""
    lines = [FLEET_BEGIN_LINE]
    if not rows:
        lines.append(_EMPTY_NOTE)
    else:
        lines.append("- Fleet:")
        for r in rows:
            lines.append("    - %s:" % _q(r["name"]))
            lines.append("        href: %s" % _q(r["href"]))
            lines.append("        description: %s" % _q(r["description"]))
            if r.get("icon"):
                lines.append("        icon: %s" % _q(r["icon"]))
    lines.append(FLEET_END_LINE)
    return "\n".join(lines) + "\n"


def services_after(current_text, fleet, inv):
    """The new services.yaml text: render the fleet block from (fleet x inv) and splice it into `current_text`
    via the editor's shared `homepage.splice_fleet_block` (replace-in-place or append). PURE."""
    rows = fleet_rows(fleet, inv)
    _assert_safe(rows)
    return homepage.splice_fleet_block(current_text, render_fleet_block(rows)), rows


def main(argv):
    # The committed example fleet span is the PUBLIC, example-derived reference (F3): `--check` VALIDATES it and
    # `--example` REGENERATES it from instance.example/ (TEST-NET addrs only — no real topology in the shipped
    # tree, which make-bundle does NOT strip). The bare write (deploy-stack, live) reads the instance OVERLAY via
    # paths.resolve and splices into the private instance/ services.yaml — instance state, stripped from the
    # bundle, never committed to origin. (The homepage files are NOT in paths._OVERLAY_MAP, so the TARGET path is
    # mode-branched literally here, mirroring homepage.py._hp_path / kontroll-init._personalize_homepage.)
    if "--check" in argv or "--example" in argv:
        fleet = _load("instance.example/fleet.yml")
        inv = inventory.merged_inventory("instance.example/inventory/hosts.yml")
        target = os.path.join(ROOT, "instance.example", "dashboards", "homepage", "services.yaml")
    else:
        fleet = _load(paths.resolve("config/fleet.yml"))
        inv = inventory.merged_inventory(paths.resolve("ansible/inventory/hosts.yml"))
        target = os.path.join(paths.ROOT, "instance", "dashboards", "homepage", "services.yaml")
    current = _read_text(target)
    want, rows = services_after(current, fleet, inv)
    rel = os.path.relpath(target, ROOT)

    if "--check" in argv:
        if current != want:
            print("STALE homepage fleet block — re-run scripts/gen-homepage.py --example:\n  " + rel)
            return 1
        print("homepage fleet block up to date (%s, %d tile(s))" % (rel, len(rows)))
        return 0

    if current != want:
        with open(target, "w", encoding="utf-8", newline="\n") as fh:   # LF on every platform (stable span)
            fh.write(want)
        print("wrote %s (%d fleet tile(s))" % (rel, len(rows)))
    else:
        print("%s already up to date (%d fleet tile(s))" % (rel, len(rows)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
