#!/usr/bin/env python3
"""scripts/gen-prometheus-jobs.py — Prometheus scrape JOBS for proxy-exporter methods, GENERATED from the
telemetry registry + the enabled modules (Phase 2a of the Option-A observability design).

A host-agent method (node) needs only a target file (gen-observability.py) — the inline `node` job in
prometheus.yml file_sd-globs it. A PROXY-exporter method (pve; snmp/blackbox later) also needs a JOB with a
metrics_path + a relabel that proxies the device address onto the control-node exporter. That job used to be
hand-written in prometheus.yml; this generator emits it from telemetry/<name>.yml so adding a proxy exporter
is a descriptor drop-in, NOT a prometheus.yml edit (closes gap-b). prometheus.yml stays composition-only via
`scrape_config_files: [jobs.d/*.generated.yml]` (relative to the config dir, so the glob resolves at host
lint time -> prometheus/jobs.d/ AND in the container -> /etc/prometheus/jobs.d/).

One file per job: prometheus/jobs.d/<job>.generated.yml (a top-level list of scrape configs), rendered in
prometheus.yml's hand-authored style (yamllint-clean: indent-sequences). The standard multi-target relabel
(__address__ -> __param_<target_param> -> instance; __address__ -> <exporter_address>) is derived from the
descriptor. Phase 2a carries only operator-owned descriptor values (no caller input); param-bearing methods
(Phase 3 snmp) add structural escaping for their attacker-influenceable params.

Standalone except kontroll.catalog (no ansible). Kept honest by `--check` (a tests/validate step).

Usage:  python3 scripts/gen-prometheus-jobs.py [--check]
"""
import glob
import os
import sys

import yaml

from kontroll import catalog, paths

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = ("# GENERATED by scripts/gen-prometheus-jobs.py from instance/fleet.yml + modules/<key>/module.yml\n"
          "# + telemetry/<method>.yml. Do NOT edit by hand — change a module's metrics method or the\n"
          "# telemetry descriptor and re-run (deploy-stack regenerates it before bringing Prometheus up).\n")


def _load(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def _render_job(method):
    """One proxy-exporter scrape job. A scrape_config_files file is a MAPPING with a top-level
    `scrape_configs:` key (Prometheus unmarshals it into config.ScrapeConfigs, NOT a bare list), so the job
    list is nested under it. Rendered in prometheus.yml's hand-authored style (yamllint-clean)."""
    job = method["job"]
    param = method.get("target_param", "target")
    lines = [
        "scrape_configs:",
        "  - job_name: %s" % job,
        "    metrics_path: %s" % method["metrics_path"],
        "    file_sd_configs:",
        '      - files: ["/etc/prometheus/targets/%s/*.yml"]' % job,
        "    relabel_configs:",
        "      - source_labels: [__address__]",     # the device addr from the generated target file
        "        target_label: __param_%s" % param,  # -> ?<param>=<device>: which device the exporter queries
        "      - source_labels: [__param_%s]" % param,
        "        target_label: instance",            # label each series by the queried device
        "      - target_label: __address__",
        "        replacement: %s" % method["exporter_address"],   # but always actually scrape the exporter
    ]
    return "\n".join(lines) + "\n"


def jobs_files(fleet, methods=None):
    """-> {repo_rel_path: rendered_body}: one prometheus/jobs.d/<job>.generated.yml per proxy-exporter method
    used by an enabled module. Host-agent methods need no job (the inline file_sd job globs their targets).
    Fails loud if two methods claim the same prometheus job name."""
    if methods is None:
        methods = {m["name"]: m for m in catalog.load_telemetry()}
    owner = {}                          # job -> the method name that owns it (one method per job)
    for key in fleet.get("enabled_modules") or []:
        mp = "modules/%s/module.yml" % key
        if not os.path.exists(os.path.join(ROOT, mp)):
            continue
        for met in (_load(mp).get("metrics") or []):
            method = methods.get(met.get("method"))
            if method and method.get("kind") == "proxy-exporter":
                job = method["job"]
                if owner.get(job, method["name"]) != method["name"]:
                    sys.exit("gen-prometheus-jobs: telemetry methods %r and %r both claim prometheus job %r"
                             % (owner[job], method["name"], job))
                owner[job] = method["name"]
    return {"prometheus/jobs.d/%s.generated.yml" % job: HEADER + _render_job(methods[name])
            for job, name in owner.items()}


def main(argv):
    fleet = _load(paths.resolve("config/fleet.yml"))
    want = {os.path.normpath(os.path.join(ROOT, rel)): body for rel, body in jobs_files(fleet).items()}
    have = {os.path.normpath(p)
            for p in glob.glob(os.path.join(ROOT, "prometheus", "jobs.d", "*.generated.yml"))}

    if "--check" in argv:
        stale = []
        for path, body in want.items():
            cur = open(path, encoding="utf-8").read() if os.path.exists(path) else None
            if cur != body:
                stale.append(os.path.relpath(path, ROOT))
        for path in have - set(want):
            stale.append(os.path.relpath(path, ROOT) + " (orphaned)")
        if stale:
            print("STALE prometheus jobs — re-run scripts/gen-prometheus-jobs.py:\n  " + "\n  ".join(stale))
            return 1
        print("prometheus jobs up to date (%d file(s))" % len(want))
        return 0

    for path in have - set(want):            # prune orphans first (a removed proxy method/module)
        os.remove(path)
    for path, body in want.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:   # LF on every platform (stable lockfile)
            fh.write(body)
    print("wrote %d job file(s): %s"
          % (len(want), ", ".join(sorted(os.path.relpath(p, ROOT) for p in want))))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
