#!/usr/bin/env python3
"""Generate the UNIFIED secret->env manifest from BOTH the telemetry and logging registries x the enabled modules.

A device/consumer method (telemetry/<m>.yml OR logging/<m>.yml) declares, as DATA, the env vars its container reads
from docker/.env and how each is composed from a SOPS domain:

    secret_domain: proxmox                 # instance/secrets/proxmox.sops.yml — the fields the templates reference
    secret_env_map:                        # {ENV_VAR: "<str.format template over that domain's field NAMES>"}
      PVE_EXPORTER_USER:      "{proxmox_api_user}"                              # 1-field (degenerate template)
      KONTROLL_PVE_LOG_TOKEN: "{proxmox_api_user}!{proxmox_api_token_id}={...}" # N-field composed token

This generator collects every (ENV_VAR -> {secret_domain, template}) an enabled module references via its `metrics:`
(telemetry) or `logs:` (logging) block and emits ONE value-free manifest deploy-stack consumes: deploy-stack
decrypts each referenced domain BY NAME (instance/secrets/<domain>.sops.yml) under no_log and composes <ENV>=<value>
into .env via the kontroll_render_token filter (fail-soft to '' if the domain/field is absent). So a NEW credentialed
exporter or log-pull is a pure drop-in — zero deploy-stack edit, zero per-domain lookup, zero hardcoded domain map.

A 1-field map is the degenerate `'{field}'` case of an N-field token, so ONE filter renders both with no branch (the
telemetry `secret_env_map` and the former logging `auth_injection` are unified under this ONE block).

Holds ZERO secret VALUES — only env-var NAMES, domain NAMES, and field-NAME templates (C12). Fail-CLOSED at GENERATE
time on a malformed descriptor: a non-UPPER_SNAKE env name, an env name colliding with a PLATFORM-CORE .env var (a
device descriptor must never shadow the control plane's own creds), an unsafe/format-spec template field, a method
declaring secret_env_map without a secret_domain, or two methods claiming the same env var with a different
(domain, template). The per-secret fail-SOFT (absent domain -> empty value) is deploy-stack's job, not the generator's.
Kept honest by --check (in tests/validate + an in-pytest twin).

Usage:  python3 scripts/gen-secret-env.py [--check]
"""
import glob
import os
import re
import string
import sys

import yaml

from kontroll import catalog, paths

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST_REL = "config/secret-env.manifest.generated.yml"      # ansible-consumed; NOT a Vector/compose config-dir

_SAFE_ENV = re.compile(r"^[A-Z][A-Z0-9_]*$")                   # an UPPER_SNAKE env-var name (lifted from gen-logging)
_SAFE_FIELD = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")         # a bare SOPS field identifier (no path/index/metachar)

# The PLATFORM-CORE .env vars deploy-stack renders as explicit, fail-CLOSED lines from the REQUIRED semaphore +
# dashboards domains (the intrinsic control-plane creds every install has — they do NOT grow with the fleet, so they
# stay hardcoded; SECURITY.md C12 / docs/reviews/2026-06-17-secret-injection/). A device/consumer secret_env_map must
# NEVER emit one of these: the render loop runs AFTER the platform-core literals, so a duplicate key could shadow the
# control plane's own admin password. This set MIRRORS the platform-core lines in deploy-stack.yml's .env render and
# is drift-pinned by tests/unit/test_gen_secret_env.py (so it can't silently fall out of sync).
RESERVED_PLATFORM_CORE_ENV = frozenset({
    "KONTROLL_MGMT_IP", "KONTROLL_DOMAIN",
    "SEMAPHORE_DB_PASSWORD", "SEMAPHORE_ADMIN", "SEMAPHORE_ADMIN_PASSWORD", "SEMAPHORE_ADMIN_EMAIL",
    "SEMAPHORE_ACCESS_KEY_ENCRYPTION", "GRAFANA_ADMIN_PASSWORD",
    "LOKI_RETENTION_PERIOD", "PROM_RETENTION_TIME", "PROM_RETENTION_SIZE",
    "KONTROLL_AUDIT_MAX_MB", "KONTROLL_AUDIT_MAX_FILES",
    "KONTROLL_OPERATOR_HOME", "KONTROLL_STORAGE_ROOT", "KONTROLL_LOGS_DIR", "KONTROLL_BACKUPS_DIR",
    "KONTROLL_API_AUDIT_DIR", "KONTROLL_GUI_AUDIT_DIR", "KONTROLL_ANSIBLE_LOG_DIR",
    "KONTROLL_JOURNAL_GID",   # the host systemd-journal GID (deploy-stack getent) for non-root Vector's group_add
    "GUI_USER", "GUI_PASSWORD", "GUI_TLS_CERT", "GUI_TLS_KEY",
    "KONTROLL_API_UVICORN_EXTRA", "KONTROLL_API_TOKEN", "KONTROLL_STAGE_PUSHES", "KONTROLL_CANONICAL_MODE",
    "KONTROLL_VECTOR_IMAGE",   # the gated custom Vector image tag (file_tail_ssh); not fleet-growing -> platform-core
    "KONTROLL_CODE_ROOT", "KONTROLL_WRITE_ROOT",   # Phase-B bake-code: gated code-root + propose write-root (api flip)
})

HEADER = (
    "# GENERATED by scripts/gen-secret-env.py — the UNIFIED secret->env manifest, keyed by env var: per enabled\n"
    "# module's referenced telemetry (metrics:) + logging (logs:) methods that declare secret_env_map, the env\n"
    "# var's SOPS secret_domain + a str.format template over that domain's field NAMES. Holds ZERO secret values\n"
    "# — only names. deploy-stack decrypts each referenced domain BY NAME (instance/secrets/<domain>.sops.yml)\n"
    "# under no_log and composes <env>=<value> into .env via the kontroll_render_token filter (fail-soft to '').\n"
    "# Do NOT edit by hand — change a method's secret_env_map and re-run gen-secret-env.\n")


def _load(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def _validate_template_or_exit(tmpl, env, name, axis, key):
    """The str.format template is an injection sink (it splices into a `.env` line via kontroll_render_token), so its
    placeholders are a CLOSED allow-list: bare `{identifier}` fields + literal text only — NO format-spec (`{x:..}`),
    conversion (`{x!r}`), index/attribute (`{x[0]}`/`{x.y}`), or metacharacter field. Fail-closed at generate time."""
    try:
        parsed = list(string.Formatter().parse(tmpl))
    except Exception as exc:
        sys.exit("gen-secret-env: %s %s method %r secret_env_map[%s] template %r is unparseable (%s)"
                 % (axis, key, name, env, tmpl, exc))
    for _literal, field, spec, conv in parsed:
        if field is None:
            continue
        if spec or conv or not _SAFE_FIELD.match(field):
            sys.exit("gen-secret-env: %s %s method %r secret_env_map[%s] template %r references an unsafe field %r "
                     "(bare {identifier} placeholders only — no format-spec/conversion/metacharacter)"
                     % (axis, key, name, env, tmpl, field))


def _validate_or_exit(method, key, axis):
    """Fail-closed shape guard for a method's secret_env_map (the unified analogue of gen-logging's former
    _validate_auth_injection_or_exit): a non-empty mapping of UPPER_SNAKE env name -> non-empty str.format template;
    a method declaring it MUST name a secret_domain; no env name may shadow a PLATFORM-CORE var; every template
    field is a safe bare identifier. Returns the validated map (or {} if absent)."""
    sem = method.get("secret_env_map")
    if sem is None:
        return {}
    name = method.get("name")
    if not isinstance(sem, dict) or not sem:
        sys.exit("gen-secret-env: %s %s method %r secret_env_map must be a non-empty mapping" % (axis, key, name))
    if not method.get("secret_domain"):
        sys.exit("gen-secret-env: %s %s method %r declares secret_env_map but no secret_domain" % (axis, key, name))
    for env, tmpl in sem.items():
        if not isinstance(env, str) or not _SAFE_ENV.match(env):
            sys.exit("gen-secret-env: %s %s method %r secret_env_map key %r must be an UPPER_SNAKE env name"
                     % (axis, key, name, env))
        if env in RESERVED_PLATFORM_CORE_ENV:
            sys.exit("gen-secret-env: %s %s method %r secret_env_map key %r collides with a PLATFORM-CORE .env var "
                     "— a device/consumer descriptor must NEVER shadow the control plane's own creds (C12)"
                     % (axis, key, name, env))
        if not isinstance(tmpl, str) or not tmpl.strip():
            sys.exit("gen-secret-env: %s %s method %r secret_env_map[%s] must be a non-empty template string"
                     % (axis, key, name, env))
        _validate_template_or_exit(tmpl, env, name, axis, key)
    return sem


def _collect(fleet, methods, block):
    """Walk enabled modules' <block> entries (`metrics:` or `logs:`), resolve each to its method descriptor, and
    accumulate its secret_env_map -> {env: {secret_domain, template}}. ONE entry per env var even if a method is
    declared on several classes; a SECOND method claiming the same env var with a DIFFERENT (domain, template) exits
    non-zero (a silent env-var collision would overwrite one method's secret)."""
    axis = "telemetry" if block == "metrics" else "logging"
    out = {}
    for key in fleet.get("enabled_modules") or []:
        mp = "modules/%s/module.yml" % key
        if not os.path.exists(os.path.join(ROOT, mp)):
            continue
        for entry in (_load(mp).get(block) or []):
            method = methods.get(entry.get("method"))
            if not method:                                  # the axis generator already fail-closes on an unknown one
                continue
            for env, tmpl in _validate_or_exit(method, key, axis).items():
                rec = {"secret_domain": method["secret_domain"], "template": tmpl}
                if env in out and out[env] != rec:
                    sys.exit("gen-secret-env: env var %r claimed twice with different (domain, template): %r vs %r"
                             % (env, out[env], rec))
                out[env] = rec
    return out


def secret_env_files(fleet):
    """-> {MANIFEST_REL: body}: the value-free unified manifest, a MAPPING keyed by env var (a mapping, not a
    sequence, so the generated YAML passes yamllint/ansible-lint indentation). ALWAYS emit (empty `env: {}` when no
    enabled method declares a secret_env_map) so --check stays honest on a fleet that onboards/removes a credentialed
    method. NO secret value."""
    tele = {m["name"]: m for m in catalog.load_telemetry()}
    logg = {m["name"]: m for m in catalog.load_logging()}
    env = dict(_collect(fleet, tele, "metrics"))
    for k, v in _collect(fleet, logg, "logs").items():       # union across axes; a cross-axis collision fail-closes too
        if k in env and env[k] != v:
            sys.exit("gen-secret-env: env var %r claimed by both a telemetry and a logging method: %r vs %r"
                     % (k, env[k], v))
        env[k] = v
    manifest = {"env": {k: env[k] for k in sorted(env)}}
    return {MANIFEST_REL: HEADER + yaml.safe_dump(manifest, sort_keys=False, default_flow_style=False)}


def main(argv):
    fleet = _load(paths.resolve("config/fleet.yml"))
    want = {os.path.normpath(os.path.join(ROOT, rel)): body for rel, body in secret_env_files(fleet).items()}
    cfg_dir = os.path.dirname(MANIFEST_REL)
    # Prune any stale config/*.manifest.generated.yml NOT in want — this auto-removes the retired
    # logging-auth.manifest.generated.yml when the combined manifest supersedes it (the rename, no transition window).
    have = {os.path.normpath(p) for p in glob.glob(os.path.join(ROOT, cfg_dir, "*.manifest.generated.yml"))}

    if "--check" in argv:
        stale = []
        for path, body in want.items():
            cur = open(path, encoding="utf-8").read() if os.path.exists(path) else None
            if cur != body:
                stale.append(os.path.relpath(path, ROOT))
        for path in have - set(want):
            stale.append(os.path.relpath(path, ROOT) + " (orphaned)")
        if stale:
            print("STALE secret-env manifest — re-run scripts/gen-secret-env.py:\n  " + "\n  ".join(stale))
            return 1
        print("secret-env manifest up to date (%d file(s))" % len(want))
        return 0

    os.makedirs(os.path.join(ROOT, cfg_dir), exist_ok=True)
    for path in have - set(want):                # prune orphans first (the retired logging-auth manifest)
        os.remove(path)
    for path, body in want.items():
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(body)
    print("wrote %d secret-env manifest(s): %s"
          % (len(want), ", ".join(sorted(os.path.relpath(p, ROOT) for p in want))))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
