#!/usr/bin/env python3
"""The baked-code manifest — "L2b for code" (M6; phase-b synthesis §3, docs/reviews/2026-06-29-phase-b-baked-code/).

Phase B bakes the importable package `scripts/kontroll/` into the published control image at /opt/kontroll
(`chmod -R a-w`), so the three network services (api/onboard-gui/semaphore) run their actuation code FROM the
digest-pinned image instead of a writable `/repo` clone. The image digest (docker/images.lock.yml, Docker-verified
on pull) already binds the WHOLE image's bytes; M8a byte-identity-checks the top-level promote slice. This generator
adds the missing middle layer: a COMMITTED, human-reviewable, per-file sha256 manifest of the baked package — the
code-world analogue of L2b's recorded-sha256 floor for collection tarballs. It gives three things a digest alone
does not: (1) a reviewable in-git record of exactly which code bytes ride the world-pullable image; (2) a `--check`
staleness gate (validate + the publish `gate` job) so the recorded floor can never silently drift from the source
that gets baked; (3) a `--verify <tree>` verb an operator/audit runs against a materialized baked tree
(`/opt/kontroll`) to prove the running code == the recorded, reviewed manifest, fail-closed on any mismatch.

Scope is exactly `scripts/kontroll/**/*.py` (the importable actuation package). The top-level promote slice
(scripts/kontroll-promote.py, scripts/gen-requirements.py) is covered by M8a byte-identity; the whole image by its
sha256 digest. This is the recorded floor for the package those layers don't enumerate file-by-file.

Modes (all OFFLINE — pure file reads, no network; the BRICK-1 discipline):
  * (default, no flag): WRITE docker/code-manifest.lock.yml from the current source tree (regenerate after any
    scripts/kontroll/ change — validate's --check fails loudly until you do).
  * --check : recompute from the source tree, diff against the committed lock; exit 1 on any added / removed /
    changed file (the staleness gate). NO network.
  * --verify <tree> : compute the manifest of <tree>/scripts/kontroll/ and compare to the committed lock; exit 1 on
    mismatch (the L2b-for-code verify — point it at /opt/kontroll on a baked node, or a kit, to prove no tamper).

Usage:  python3 scripts/gen-code-manifest.py [--check | --verify <code-tree-root>]
"""
import hashlib
import os
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOCK = os.path.join(ROOT, "docker", "code-manifest.lock.yml")
PKG_REL = os.path.join("scripts", "kontroll")   # the baked importable package, relative to a code-tree root


def sha256_file(path):
    """The streamed sha256 hex digest of one file (PURE read — the per-file artifact hash the manifest records)."""
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def compute(root=ROOT):
    """Walk <root>/scripts/kontroll for *.py and return {repo-relative-posix-path: sha256hex}, deterministically.

    Keys are repo-relative with forward slashes (so the lock is byte-stable across OSes and `--verify <tree>` can
    rejoin them onto any code-tree root). PURE read; no network. Skips __pycache__ (never baked / never committed)."""
    pkg = os.path.join(root, PKG_REL)
    out = {}
    for dirpath, dirnames, filenames in os.walk(pkg):
        dirnames[:] = [d for d in dirnames if d != "__pycache__"]
        for name in filenames:
            if not name.endswith(".py"):
                continue
            abspath = os.path.join(dirpath, name)
            rel = os.path.relpath(abspath, root).replace(os.sep, "/")
            out[rel] = sha256_file(abspath)
    return out


def render(manifest):
    """Byte-exact, yamllint-clean lock content (hand-rendered so it stays diff-minimal + line-length-clean across
    releases — the bare 64-hex value keeps every line under 120; the algorithm is fixed by `schema`)."""
    s = ("---\n"
         "# GENERATED by scripts/gen-code-manifest.py — DO NOT hand-edit. Run the generator to refresh.\n"
         "# M6 \"L2b for code\" (phase-b synthesis §3): the recorded sha256 floor for the baked importable package\n"
         "# scripts/kontroll/ — the code the network services run from the digest-pinned control image at\n"
         "# /opt/kontroll. validate + the publish gate run `--check` to keep this honest with the source that gets\n"
         "# baked; `gen-code-manifest.py --verify <tree>` re-checks a materialized baked tree (fail-closed on drift).\n"
         "# Parallel to docker/images.lock.yml (the image-BYTE floor) + M8a (byte-identity of the promote slice).\n"
         "# Values are the sha256 hex of each file (fixed algorithm; no prefix to stay line-length-clean).\n"
         "schema: 1\n"
         "files:\n")
    for rel in sorted(manifest):
        s += "  %s: \"%s\"\n" % (rel, manifest[rel])
    return s


def load(path=LOCK):
    """The committed manifest as {path: sha256hex} (or {} if absent — a first-run / missing lock)."""
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as fh:
        return (yaml.safe_load(fh) or {}).get("files") or {}


def diff(recorded, computed):
    """Return a list of human-readable problems comparing the recorded floor to a freshly-computed manifest ([] ==
    in sync). Catches ADDED (a new baked file not yet recorded — no silent un-cover), REMOVED (a recorded file that
    no longer exists), and CHANGED (a recorded file whose bytes drifted) — all fail-closed for --check / --verify."""
    problems = []
    for path in sorted(set(computed) - set(recorded)):
        problems.append("ADDED (not in the recorded floor — regenerate): %s" % path)
    for path in sorted(set(recorded) - set(computed)):
        problems.append("REMOVED (recorded but absent from the tree): %s" % path)
    for path in sorted(set(recorded) & set(computed)):
        if recorded[path] != computed[path]:
            problems.append("CHANGED (sha256 drift under a recorded pin): %s" % path)
    return problems


def write():
    # newline="\n": the committed lock is byte-identical regardless of the OS it's regenerated on (a Windows text-mode
    # write would emit CRLF), so a cross-OS regenerate produces a diff-minimal, normalized artifact.
    with open(LOCK, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render(compute()))
    print("gen-code-manifest: wrote %s (%d files)" % (os.path.relpath(LOCK, ROOT), len(compute())))


def main(argv=None):
    args = list(sys.argv[1:] if argv is None else argv)
    if "--check" in args:
        problems = diff(load(), compute())
        if problems:
            sys.stderr.write("code-manifest.lock.yml is STALE — `python3 scripts/gen-code-manifest.py` to refresh:\n")
            for p in problems:
                sys.stderr.write("  %s\n" % p)
            sys.exit(1)
        print("gen-code-manifest: code-manifest.lock.yml in sync with scripts/kontroll/ (--check)")
        return
    if "--verify" in args:
        rest = [a for a in args if not a.startswith("--")]
        if not rest:
            sys.stderr.write("--verify needs a code-tree root (e.g. --verify /opt/kontroll)\n")
            sys.exit(2)
        tree = rest[0]
        problems = diff(load(), compute(tree))
        if problems:
            sys.stderr.write("VERIFY FAILED: %s/scripts/kontroll does not match the recorded floor:\n" % tree)
            for p in problems:
                sys.stderr.write("  %s\n" % p)
            sys.exit(1)
        print("gen-code-manifest: %s/scripts/kontroll matches the recorded manifest (--verify)" % tree)
        return
    write()   # default: regenerate the committed lock


if __name__ == "__main__":
    main()
