#!/usr/bin/env python3
"""scripts/gen-snmp.py — the snmp_exporter `if_mib` modules block, GENERATED from a committed generator.yml
+ a vendored public MIB closure, replacing the hand-authored block in prometheus/exporters/snmp/snmp.yml.j2.

no-bespoke-config tenet: the if_mib OID set is DERIVED from public IETF MIBs (mibs/, net-snmp v5.9 + IANA),
pinned + validated, never bespoke — so MIB/vendor churn is a reviewable diff. Same generated-artifact + --check
seam as the other gen-* (gen-exporters/gen-observability/...), with one wrinkle: the actual generator is a
NetSNMP/CGO Go binary (no static binary, no reliable image — upstream #944), so REGENERATION is CI/VM-only
(libsnmp + a CGO build of snmp_exporter generator v0.30.1 — see prometheus/exporters/snmp/README.md).

Two paths, mirroring the upstream-tool/committed-artifact split:
  * REGENERATE (no flag): run the pinned generator -> parse its output -> take ONLY `modules` -> re-dump through
    the in-repo _Indent SafeDumper (yamllint-clean, LF). This STRIPS the generator's `# WARNING` banner AND the
    `auths:` block it copies verbatim, so the committed artifact is modules-ONLY and carries no secret. Requires
    the generator binary -> CI/VM only (the .github CGO job + the control VM).
  * --check (no binary): pure-Python staleness/secret gate over the committed modules.generated.yml — present,
    non-empty, parses, top-level `modules:` ONLY (no auths:), contains if_mib, no credential substring. Runs in
    the existing CI-only validator tier (tests/validate.sh) + the hermetic pytest twin. The byte-exact
    "generated == a fresh rebuild" gate lives in the dedicated CGO CI job (regenerate + `git diff --exit-code`).
The FAITHFUL-migration proof (generated module == the frozen 7-OID/6-metric oracle) is tests/unit/test_gen_snmp.py.

Usage:  python3 scripts/gen-snmp.py [--check]
"""
import os
import shutil
import subprocess
import sys
import tempfile

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SNMP_DIR = os.path.join("prometheus", "exporters", "snmp")
GENERATOR_YML = os.path.join(SNMP_DIR, "generator.yml")
MIBS_DIR = os.path.join(SNMP_DIR, "mibs")
MODULES_OUT = os.path.join(SNMP_DIR, "modules.generated.yml")

# Credential field-names that must NEVER appear in the committed (public) modules artifact — the generator
# copies `auths:` verbatim into its output, so this is the belt to the structural check's suspenders (SEC1).
_SECRET_SUBSTRINGS = ("username", "password", "community", "priv_password", "auth_protocol", "priv_protocol")

HEADER = (
    "# GENERATED by scripts/gen-snmp.py from prometheus/exporters/snmp/generator.yml + the vendored MIB\n"
    "# closure (mibs/, net-snmp v5.9 + IANA), via the pinned snmp_exporter generator v0.30.1. Do NOT edit by\n"
    "# hand — change generator.yml (or the MIBs) and regenerate (CI/VM only; CGO + libsnmp). The SNMPv3 creds\n"
    "# are SOPS-templated into snmp.yml at deploy; this file is modules: ONLY (no auths:) and carries no secret.\n"
)


class _Indent(yaml.SafeDumper):
    """Indent block sequences under their key (output passes yamllint indent-sequences: true) — same Dumper the
    other gen-* use, so the committed bytes are a function of kontroll's Python, not the Go marshaller (immunizes
    --check / the rebuild-diff against any upstream serialization change within the pinned generator version)."""
    def increase_indent(self, flow=False, indentless=False):
        return super().increase_indent(flow, False)


def _normalize(raw):
    """Generator output -> the committed modules-only body. The raw output is `# WARNING` banner + `auths:` +
    `modules:` (it does NOT start with modules:); take ONLY `modules` and re-dump, so the artifact is
    modules-rooted (valid for the snmp.yml.j2 {% include %}), banner-free, auths-free, and yamllint-clean."""
    cfg = yaml.safe_load(raw) or {}
    modules = cfg.get("modules")
    if not modules or "if_mib" not in modules:
        sys.exit("gen-snmp: generator output has no modules.if_mib — check generator.yml + the MIB closure")
    body = yaml.dump({"modules": modules}, Dumper=_Indent, sort_keys=False,
                     default_flow_style=False, indent=2, width=4096)
    return HEADER + body


def _find_generator():
    """The pinned snmp_exporter generator binary: $KONTROLL_SNMP_GENERATOR, else `snmp-generator`/`generator`
    on PATH. None when absent (Windows author box / bare CI) -> regeneration is CI/VM-only by design."""
    env = os.environ.get("KONTROLL_SNMP_GENERATOR")
    if env and os.path.exists(env):
        return env
    for name in ("snmp-generator", "generator"):
        found = shutil.which(name)
        if found:
            return found
    return None


def regenerate():
    """Run the pinned generator against the committed generator.yml + vendored mibs/ and return the normalized
    modules-only body. CI/VM only (needs the CGO binary). `--fail-on-parse-errors` => a missing MIB import
    (e.g. SNMPv2-CONF) is a hard, loud failure, never a silently degraded module (fail-closed)."""
    gen = _find_generator()
    if not gen:
        sys.exit("gen-snmp: generator binary not found (set KONTROLL_SNMP_GENERATOR, or put snmp-generator on "
                 "PATH). Regeneration is CI/VM-only (CGO + libsnmp); on Windows use --check. See %s/README.md."
                 % SNMP_DIR)
    with tempfile.TemporaryDirectory() as td:
        out = os.path.join(td, "snmp.full.yml")
        env = dict(os.environ, MIBDIRS=os.path.join(ROOT, MIBS_DIR))
        proc = subprocess.run(
            [gen, "--fail-on-parse-errors", "generate",
             "-m", os.path.join(ROOT, MIBS_DIR), "-g", os.path.join(ROOT, GENERATOR_YML), "-o", out],
            env=env, capture_output=True, text=True)
        if proc.returncode != 0:
            sys.exit("gen-snmp: generator failed (rc=%d)\nstdout:\n%s\nstderr:\n%s"
                     % (proc.returncode, proc.stdout, proc.stderr))
        with open(out, encoding="utf-8") as fh:
            raw = fh.read()
    return _normalize(raw)


def _check():
    """Pure-Python staleness + secret gate over the committed modules.generated.yml (no binary). Returns 0/1."""
    path = os.path.join(ROOT, MODULES_OUT)
    if not os.path.exists(path):
        print("STALE: %s is missing — regenerate (CI/VM): python3 scripts/gen-snmp.py" % MODULES_OUT)
        return 1
    text = open(path, encoding="utf-8").read()
    if not text.strip():
        print("STALE: %s is empty" % MODULES_OUT)
        return 1
    try:
        cfg = yaml.safe_load(text) or {}
    except yaml.YAMLError as exc:
        print("INVALID: %s does not parse: %s" % (MODULES_OUT, exc))
        return 1
    if set(cfg) != {"modules"}:
        print("INVALID: %s must contain ONLY a top-level `modules:` mapping (got %s) — the generator's auths: "
              "must be stripped" % (MODULES_OUT, sorted(cfg)))
        return 1
    if "if_mib" not in (cfg.get("modules") or {}):
        print("INVALID: %s has no modules.if_mib — the allow-list (telemetry/snmp.yml) + the cisco_ios/"
              "fortigate selectors require the name `if_mib`" % MODULES_OUT)
        return 1
    # Scan the PARSED data (re-dumped, comment-free) so this file's own header prose can't false-positive; the
    # structural check above already proves there is no auths: block.
    data = yaml.safe_dump(cfg).lower()
    leaked = [s for s in _SECRET_SUBSTRINGS if s in data]
    if leaked:
        print("SECRET LEAK: %s contains credential field name(s) %s — it must be PUBLIC modules only"
              % (MODULES_OUT, leaked))
        return 1
    print("snmp modules.generated.yml: present, modules-only, if_mib, no-secret (OK)")
    return 0


def main(argv):
    if "--check" in argv:
        return _check()
    body = regenerate()
    with open(os.path.join(ROOT, MODULES_OUT), "w", encoding="utf-8", newline="\n") as fh:   # LF on every platform
        fh.write(body)
    print("wrote %s (%d bytes)" % (MODULES_OUT, len(body)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
