#!/usr/bin/env python3
"""Generate the Semaphore backup-schedule spec from each enabled class's `backup:` block + the inventory.

A device class declares its backup shape AS DATA in modules/<key>/module.yml — the secondary-capability
`backup:` block (instance #2 of the generalized capability seam):

    backup:
      capable: true            # mirrors roles/<role>/defaults/main.yml backup_capable
      schedule: "0 2 * * *"    # cron — when Semaphore runs THIS class's config capture

This generator JOINs enabled modules (instance/fleet.yml) x their `backup:` block, validates each capable class
has a role backup entrypoint (`roles/<role>/tasks/backup.yml` — the same `device_role` dispatch
backup-configs.yml uses), and writes config/semaphore/schedules.generated.yml — one schedule per backup-capable
class, **limited to that class's inventory_group** (so each class is captured on its own cron, not a single
fleet-wide run). scripts/configure-semaphore.py consumes it — so adding a per-class backup schedule is a
`backup:` drop-in, NOT an edit to configure-semaphore.py (it removes the hand-listed nightly-backup hub).

Fail-closed: a class `capable: true` with no `schedule`, or whose role has no `tasks/backup.yml`, exits
non-zero (never a silent missing schedule). The output is a GENERATED lockfile kept honest by `--check` (a
tests/validate step). Standalone — no ansible (the one kontroll import, paths, is os-only: the instance-overlay
resolver); mirrors gen-observability.py.

Usage:  python3 scripts/gen-backup.py [--check]
"""
import glob
import os
import sys

import yaml

from kontroll import paths

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = "config/semaphore/schedules.generated.yml"
HEADER = ("# GENERATED by scripts/gen-backup.py from instance/fleet.yml + the modules/<key>/module.yml `backup:`\n"
          "# blocks. Do NOT edit by hand — change a module's `backup:` block and re-run (configure-semaphore.py\n"
          "# consumes this to register the per-class Semaphore schedules).\n")


def _load(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def _module(key):
    """The modules/<key>/module.yml dict, or None if absent — the I/O seam the tests monkeypatch."""
    mod_rel = "modules/%s/module.yml" % key
    if not os.path.exists(os.path.join(ROOT, mod_rel)):
        return None
    return _load(mod_rel)


def _role_has_backup(role):
    """Whether roles/<role>/tasks/backup.yml exists — the per-class backup entrypoint backup-configs.yml
    dispatches to via device_role. A seam, so the fail-closed branch is testable without a real role tree."""
    return os.path.exists(os.path.join(ROOT, "ansible", "roles", role, "tasks", "backup.yml"))


def backup_schedules(fleet):
    """-> the schedule specs (one per backup-capable class declaring a schedule). Each is
    {name, cron, limit, key, playbook}. Fail-closed: capable-without-schedule or a missing role backup
    entrypoint exits non-zero. A `backup:` block with capable:false is a declared NON-capture (no schedule)."""
    out = []
    for key in fleet.get("enabled_modules") or []:
        module = _module(key)
        if module is None:
            continue
        bk = module.get("backup")
        if not bk or not bk.get("capable"):
            continue
        role = module.get("role") or key
        if not _role_has_backup(role):
            sys.exit("gen-backup: %s is backup.capable but role %r has no tasks/backup.yml "
                     "(add the role's backup entrypoint, or set capable: false)" % (key, role))
        sched = bk.get("schedule")
        if not sched:
            sys.exit("gen-backup: %s is backup.capable but declares no `schedule` (cron required)" % key)
        spec = {"name": "backup-%s" % key, "cron": str(sched),
                "limit": module.get("inventory_group"), "key": key,
                "playbook": "ansible/playbooks/backup-configs.yml"}
        # Optional knobs (#123) — carried ONLY when the block declares them, so a class without them (every
        # shipped class today) keeps a byte-identical spec and the --check lockfile stays stable. `retention` is
        # ALSO passed to the run as kontroll_backup_retention by configure-semaphore; `destination` is recorded.
        if bk.get("retention"):
            spec["retention"] = str(bk["retention"])
        if bk.get("destination"):
            spec["destination"] = str(bk["destination"])
        out.append(spec)
    return out


def render(specs):
    """The generated YAML — a mapping with a top-level `schedules:` list (configure-semaphore.py reads it).
    Hand-rendered (like gen-observability) with INDENTED sequence items, so the lockfile is yamllint-clean
    (`indent-sequences: true`); the cron is quoted (a leading `*`/`0` plain scalar is fragile)."""
    lines = [HEADER.rstrip("\n")]
    if not specs:
        lines.append("schedules: []")
        return "\n".join(lines) + "\n"
    lines.append("schedules:")
    for s in specs:
        lines.append("  - name: %s" % s["name"])
        lines.append('    cron: "%s"' % s["cron"])
        lines.append("    limit: %s" % (s["limit"] or "all"))
        lines.append("    key: %s" % s["key"])
        lines.append("    playbook: %s" % s["playbook"])
        if s.get("retention"):                       # optional knobs (#123) — only when declared (keeps the lockfile stable)
            lines.append("    retention: %s" % s["retention"])
        if s.get("destination"):
            lines.append("    destination: %s" % s["destination"])
    return "\n".join(lines) + "\n"


def main(argv):
    fleet = _load(paths.resolve("config/fleet.yml"))
    specs = backup_schedules(fleet)
    body = render(specs)
    path = os.path.join(ROOT, OUT)
    if "--check" in argv:
        cur = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        # an orphaned spec (no class declares backup anymore) is also stale
        orphan = bool(glob.glob(os.path.join(ROOT, "config", "semaphore", "*.generated.yml"))) and not specs and cur
        if cur != body or orphan:
            print("STALE %s — re-run scripts/gen-backup.py" % OUT)
            return 1
        print("backup schedules up to date (%d schedule(s))" % len(specs))
        return 0
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(body)
    print("wrote %s (%d schedule(s))" % (OUT, len(specs)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
