#!/usr/bin/env python3
"""Generate Vector logging config from the enabled device modules + the inventory — the logging analogue of
gen-observability.py (the capability-derived half of docs/logging-architecture.md §3.5).

Each device class declares its log sources AS DATA in modules/<key>/module.yml by referencing a logging METHOD
by name (the registry, logging/<name>.yml):

    logs:                                   # a list — a class may emit several log sources
      - {method: syslog_push, params: {transport: tcp}}

This generator loads the logging-method registry (catalog.load_logging), then JOINS enabled modules
(instance/fleet.yml) x their logs entries x the inventory hosts in each module's inventory_group, and writes
ONE full-config Vector fragment per (method, key) into docker/vector/generated/ — a SOURCE + a shaping
TRANSFORM with EXPLICIT component ids (NOT config.d implicit namespacing, so the ids never collide and
`vector validate` is predictable) — plus a single aggregate `loki` SINK fragment consuming every generated
transform. The fragments are loaded by a second `--config-dir /etc/vector/generated` (disjoint from the
hand-authored config.d/ tree), so adding a class's log source is a generated drop-in, NEVER a hub edit.

Fail-closed (mirrors gen-observability): an unknown/missing method, a param outside the method's CLOSED
allow-list, or a label outside the canonical NON-SECRET set (C12) exits non-zero — never a silent/empty source
and never a secret-bearing label. Standalone except for kontroll.catalog/paths (no ansible).

Usage:  python3 scripts/gen-logging.py [--check | --example]   # bare = write live drop-ins from the instance overlay;
        # --example = (re)write the committed PUBLIC lockfile from instance.example/; --check = validate it (F3)
"""
import glob
import os
import re
import sys

import yaml

from kontroll import catalog, endpoints, inventory, paths

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEN_DIR = "docker/vector/generated"          # the ONE generated tree (lockfile_glob covers it; disjoint config.d)

# --- Loki per-class retention enactment (S5) — a GENERATED runtime_config overrides file ------------------- #
# The M-1 dogfood (docs/reviews/2026-06-16-storage-logging/40-m1-loki-retention-dogfood.md) verified the seam on
# the pinned Loki 3.4.2 and CORRECTED the design's assumptions:
#   F3  with auth_enabled:false Loki's tenant is "fake" (NOT "*"); per-tenant overrides key on it EXACTLY.
#   F4  retention_stream.period MUST be >= 24h, AND an invalid overrides file is FATAL at Loki STARTUP — so the
#       generated file must ALWAYS be valid (every preset is >= 24h; absent retention => an empty `overrides:{}`).
#   replace-not-merge  a per-tenant retention_stream REPLACES the static limits_config.retention_stream for that
#       tenant, so when we emit an override we CARRY FORWARD the static baseline (debug/audit) entries — else the
#       90d audit-stream retention would silently regress to the 30d global default (a C12 data-loss).
LOKI_OVERRIDES_REL = "docker/loki/overrides/retention.generated.yaml"
LOKI_CONFIG_REL = "docker/loki/loki-config.yml"
LOKI_TENANT = "fake"   # the auth_enabled:false default tenant (M-1 F3). Change here IFF Loki auth is enabled.
_RETENTION_PRESET_HOURS = {"7d": "168h", "30d": "720h", "90d": "2160h"}   # the closed allow-list; all >= 24h (F4)
LOKI_OVERRIDES_HEADER = (
    "# GENERATED by scripts/gen-logging.py — per-class capability log retention as a Loki runtime_config\n"
    "# overrides file (hot-reloaded; period 10s). Keyed on tenant 'fake' (auth_enabled:false). Do NOT edit by\n"
    "# hand — set a `retention` param on a module's logs: entry and re-run (deploy-stack regenerates it before\n"
    "# bringing Loki up). Absent retention => `overrides: {}` (the bounded global LOKI_RETENTION_PERIOD applies).\n"
    "# M-1 seam verification: docs/reviews/2026-06-16-storage-logging/40-m1-loki-retention-dogfood.md.\n")
# The canonical, low-cardinality, NON-SECRET Loki label set (C12). gen-logging fail-closes on any label outside
# it; the capability sink labels by these only. `source`/`run_id` are sink-side; a method contributes the rest.
_CANONICAL_LABELS = {"source", "host", "service", "level", "run_id", "device"}
HEADER = ("# GENERATED by scripts/gen-logging.py from instance/fleet.yml + modules/<key>/module.yml's `logs:`\n"
          "# block + the logging/<method>.yml registry. Do NOT edit by hand — change a module's `logs:` block\n"
          "# and re-run (deploy-stack regenerates it before bringing Vector up). Loaded via the Vector\n"
          "# `--config-dir /etc/vector/generated` (full-config fragments, explicit component ids).\n")

# --- credentialed-pull token INJECTION — the value-free secret->env MANIFEST is now emitted by the UNIFIED
# scripts/gen-secret-env.py (which collects every telemetry + logging method's `secret_env_map` into ONE manifest
# deploy-stack consumes), NOT here. gen-logging keeps only the logging-specific CHECK that a credentialed pull source
# (a `source.auth.value` referencing `${ENV}`) declares that ENV in its `secret_env_map` (the single-source-of-truth
# so the env name can't drift between the Vector auth value and the manifest). The Vector container still reads the
# token from `${ENV}` via a one-line `${VAR:-}` passthrough in docker/services/vector.yaml (compose `include` can't
# merge it — hand-authored, value-free). Audit: docs/reviews/2026-06-17-secret-injection/.
_ENV_REF = re.compile(r"\$\{([A-Z][A-Z0-9_]*)\}")                    # an ${UPPER_SNAKE} interpolation in source.auth


def _load(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def _load_optional(rel):
    """Like _load but {} for an absent file — for the instance overlay config (instance.yml) that a fresh/blind
    node may not have populated yet. Used to read the OPTIONAL `device_trust` instance decisions."""
    p = os.path.join(ROOT, rel)
    if not os.path.exists(p):
        return {}
    with open(p, encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def _hosts_in_group(inv, group):
    """{hostname: ansible_host} for a leaf inventory group (all.children.<group>.hosts)."""
    node = ((inv.get("all") or {}).get("children") or {}).get(group) or {}
    return {name: (h or {}).get("ansible_host")
            for name, h in (node.get("hosts") or {}).items() if (h or {}).get("ansible_host")}


def _validate_params_or_exit(method, params, key):
    """Fail-closed: a required param missing, a value not in the method's CLOSED `allowed` list, or an unknown
    param -> sys.exit (never interpolated). The config-injection guard, identical posture to
    gen-observability's _entries param check (C12)."""
    given = params or {}
    spec = method.get("params") or {}
    for pname, pdef in spec.items():
        val = given.get(pname)
        if val is None:
            if pdef.get("required"):
                sys.exit("gen-logging: %s method %r requires param %r" % (key, method["name"], pname))
            continue
        if val not in (pdef.get("allowed") or []):
            sys.exit("gen-logging: %s param %s=%r is not in the allow-list %r for method %r "
                     "(rejected — never interpolated)" % (key, pname, val, pdef.get("allowed"), method["name"]))
    for pname in given:
        if pname not in spec:
            sys.exit("gen-logging: %s method %r takes no param %r" % (key, method["name"], pname))


def _validate_labels_or_exit(method, key):
    """Fail-closed: every label a method contributes MUST be in the canonical NON-SECRET set (C12) — a label
    outside it (a credential-bearing or high-cardinality key) exits non-zero, so a secret can never reach
    Loki's unencrypted index. The label-hygiene analogue of gen-observability's `emits unknown label` exit;
    written FRESH (gen-observability hardcodes a 2-label branch, nothing reusable to lift)."""
    for lk in method.get("labels") or []:
        if lk not in _CANONICAL_LABELS:
            sys.exit("gen-logging: %s method %r emits non-canonical/secret-risk label %r (allowed: %s)"
                     % (key, method["name"], lk, sorted(_CANONICAL_LABELS)))


def _validate_transform_vrl_or_exit(method, key):
    """Fail-closed: a method's optional `transform_vrl` (the data-driven field derivation the renderer splices
    into the shaping transform BEFORE the canonical defaults) MUST be a non-empty list of non-empty strings —
    never a bare string (which a `+= list(...)` would splice character-by-character into garbage VRL) and never
    a structured object (un-renderable). The VRL body itself is REGISTRY-authored (same trust boundary as the
    method's `source:` block); `vector validate` in CI is the semantic gate. This guard catches a malformed
    descriptor at GENERATE time — a typed-wrong transform_vrl — rather than at Vector startup (C12 config-as-
    data: a log-method descriptor is validated before it can shape an event)."""
    tv = method.get("transform_vrl")
    if tv is None:
        return
    if not isinstance(tv, list) or not tv:
        sys.exit("gen-logging: %s method %r transform_vrl must be a non-empty list of VRL line strings (got %r)"
                 % (key, method["name"], type(tv).__name__))
    for line in tv:
        if not isinstance(line, str) or not line.strip():
            sys.exit("gen-logging: %s method %r transform_vrl entries must each be a non-empty string (got %r)"
                     % (key, method["name"], line))


# a dotted field PATH of safe identifiers (no metacharacters / quotes / ${} / spaces / parens). pull_unnest is
# spliced into `unnest(.<path>)` and dedupe_key into a Vector dedupe `fields.match` path — a config-injection
# surface, so the allow-list is closed exactly like the param / transform_vrl guards.
_SAFE_FIELD_PATH = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)*$")


def _validate_pull_shape_or_exit(method, key):
    """Fail-closed: a method's OPTIONAL pull-fan fields — `pull_unnest` (the array field to fan to one event per
    element via `. = unnest(.<field>)`) and `dedupe_key` (the field path a Vector `dedupe` transform keys on to
    drop a re-ingested entry across polls) — must each be a safe dotted field PATH and may appear ONLY on a
    `direction: pull` source (a push listener has no array to fan / no re-ingestion). A metacharacter-bearing
    value or either field on a non-pull method exits non-zero at GENERATE time, before it can emit broken VRL or
    a mis-wired pipeline — the same fail-closed config-as-data posture as `_validate_transform_vrl_or_exit` (C12).
    Absent on a method => no-op (today's single-transform fragment, byte-identical)."""
    pu = method.get("pull_unnest")
    dk = method.get("dedupe_key")
    if pu is None and dk is None:
        return
    if method.get("direction") != "pull":
        sys.exit("gen-logging: %s method %r declares pull_unnest/dedupe_key but is not direction: pull"
                 % (key, method["name"]))
    for fld, val in (("pull_unnest", pu), ("dedupe_key", dk)):
        if val is None:
            continue
        if not isinstance(val, str) or not _SAFE_FIELD_PATH.match(val):
            sys.exit("gen-logging: %s method %r %s=%r must be a dotted field path of [A-Za-z_][A-Za-z0-9_]* "
                     "segments (rejected — never interpolated)" % (key, method["name"], fld, val))


def _validate_credentialed_source_or_exit(method, key):
    """Fail-closed: a CREDENTIALED pull source (a `source.auth.value` that interpolates `${ENV}`) MUST declare that
    ENV in its `secret_env_map` — the single source of truth, so the env name can't drift between the Vector auth
    value and the unified secret->env manifest (which gen-secret-env builds from `secret_env_map`). A credentialed
    source whose `${ENV}` isn't in `secret_env_map` would ship an auth header deploy-stack never fills (Vector gets
    an empty token -> silent auth failure). The manifest EMISSION + the secret_env_map SHAPE validation live in
    gen-secret-env.py; this is the logging-source-side cross-check that the auth value and the map agree (C12)."""
    auth_value = str(((method.get("source") or {}).get("auth") or {}).get("value") or "")
    refs = set(_ENV_REF.findall(auth_value))
    if not refs:
        return                                              # an uncredentialed source (journald/file/syslog) — no env
    declared = set((method.get("secret_env_map") or {}).keys())
    missing = refs - declared
    if missing:
        sys.exit("gen-logging: %s method %r source.auth.value references %s but its secret_env_map declares %s — "
                 "every ${ENV} in a credentialed source must be a secret_env_map key (single source of truth)"
                 % (key, method["name"], sorted(missing), sorted(declared) or "nothing"))


def _subst(value, mgmt_ip, device_addr):
    """Substitute the two source placeholders. ${MGMT_IP} -> 0.0.0.0 (an ingress source binds container-internal;
    the operator publishes the mgmt-bound port). ${DEVICE_ADDR} -> the device's inventory address (a pull
    source reaches out to it). Leaves all other ${...} for Vector's own runtime env interpolation.

    Recurses into LISTS and DICTS so a structured source value gets substituted element-wise — an `exec` source's
    `command:` is a LIST of argv strings (e.g. file_tail_ssh's `[..., "root@${DEVICE_ADDR}"]`), so without
    recursion the per-host pull address would never reach the ssh target. Scalars other than str pass through
    unchanged; a list/dict with no placeholder is returned byte-identical (journald_remote's static command is
    untouched)."""
    if isinstance(value, list):
        return [_subst(v, mgmt_ip, device_addr) for v in value]
    if isinstance(value, dict):
        return {k: _subst(v, mgmt_ip, device_addr) for k, v in value.items()}
    if not isinstance(value, str):
        return value
    return value.replace("${MGMT_IP}", mgmt_ip).replace("${DEVICE_ADDR}", device_addr or "127.0.0.1")


def _render_fragment(method, key, group, hosts, vendor_defaults=None, instance_trust=None):
    """A full-config Vector fragment dict for one (method, key): a SOURCE (id <m>_<k>_src) + a shaping
    TRANSFORM (id <m>_<k>_shape, inputs the source) setting the canonical labels. Explicit ids — no config.d
    namespacing. One fragment per (method, key): a PUSH source is a single listener; a PULL source targets the
    group's first host (per-host fan is a follow-up).

    The shaping VRL is in two halves. The BASELINE is GENERIC — it knows NO method-specific field name: it sets
    the structural labels (.source/.device) and the canonical-field DEFAULTS (.service/.host/.level fallbacks).
    Any method-specific field DERIVATION — a syslog source's RFC5424 `.severity` -> `.level`, a journald
    source's `._SYSTEMD_UNIT` -> `.service` — is DATA the method declares in `transform_vrl:` (logging/<m>.yml),
    spliced in BEFORE the defaults so a real derived value wins and the default is only the fallback. This is
    the data-driven shaping seam (S9): gen-logging NEVER branches on the method name (no `if method == ...`);
    a new derivation is a `transform_vrl:` edit in the drop-in registry file, not a generator change.

    A PULL method MAY additionally declare two OPTIONAL DATA fields that render extra PRE-transforms, also with
    no method-name branch: `pull_unnest: <array-field>` fans a `{<field>:[...]}` poll into one event per element
    (`. = unnest(.<field>)`), and `dedupe_key: <field-path>` drops an entry already seen across polls (a Vector
    `dedupe` transform). The fragment becomes a CHAIN `src -> [unnest] -> [dedupe] -> shape`, each optional stage
    rendered only when its field is present and the `inputs:` threaded by `prev_id` so the shape always consumes
    the last present stage. Absent => the identical 2-component fragment as today."""
    name = method["name"]
    sid = "%s_%s_src" % (name, key)
    tid = "%s_%s_shape" % (name, key)
    # For a PULL source the endpoint address and the `.host` label MUST be the SAME host — derive BOTH from one
    # sorted (name, addr) pair. Two independent sorts (sorted values for the addr, sorted keys for the label)
    # can pick DIFFERENT hosts when name-order and addr-order disagree (e.g. endpoint -> 192.0.2.11 but label
    # -> "my-hypervisor-2"), mislabeling the stream. A push listener has no ${DEVICE_ADDR}; the consistent label still wins.
    first_host, first_addr = next(iter(sorted((hosts or {}).items())), (key, None))
    src = {"type": method["kind"]}
    for k, v in (method.get("source") or {}).items():
        src[k] = _subst(v, "0.0.0.0", first_addr)

    # TLS posture from the DEVICE CLASS (no-bespoke tenet): a method that opts into `tls_from_class` gets its
    # `source.tls` resolved from the class `vendor_defaults.tls_posture` (⊕ an instance CA pin) via
    # kontroll.endpoints — NEVER a literal `tls:` in the descriptor. The SAME vendor fact telemetry derives from,
    # so the two consumers can't drift. Fail-CLOSED: a missing/unknown posture exits (never silently verify=False).
    if method.get("tls_from_class"):
        try:
            verify, ca_file = endpoints.tls_verify(vendor_defaults, instance_trust)
        except ValueError as exc:
            sys.exit("gen-logging: %s method %r tls_from_class: %s" % (key, name, exc))
        src["tls"] = {"verify_certificate": verify}
        if ca_file:
            # The operator pinned a CA (ca_file = their HOST path). Vector reads the IN-CONTAINER bundle that
            # deploy-stack assembles + vector.yaml statically mounts — NOT the raw host path. So thread the fixed
            # container target, never the operator's disk path (the host->container bind is the mount, not this).
            src["tls"]["ca_file"] = endpoints.VECTOR_CA_BUNDLE

    transforms = {}
    prev_id = sid                                       # the shape transform consumes the LAST present stage

    # Optional PULL fan-out (DATA: pull_unnest = the array field). is_array guard so a non-array/error poll
    # passes through untouched instead of erroring; the call is `unnest!` (abort-on-error) INSIDE the guard because
    # VRL's type-checker does NOT narrow `.<field>` to `array` from the `is_array` test, so a plain `unnest(.x)` is
    # a fallible assignment (E103) — the guard makes the `!` abort unreachable (dogfood-caught). NO method-name
    # branch — a generic field lookup (cf transform_vrl).
    unnest_field = method.get("pull_unnest")
    if unnest_field:
        uid = "%s_%s_unnest" % (name, key)
        transforms[uid] = {"type": "remap", "inputs": [prev_id],
                           "source": "if is_array(.%s) {\n    . = unnest!(.%s)\n}\n" % (unnest_field, unnest_field)}
        prev_id = uid

    # Optional dedupe keyed on the declared unique field path (DATA: dedupe_key) — drops a re-ingested entry.
    dedupe_key = method.get("dedupe_key")
    if dedupe_key:
        did = "%s_%s_dedupe" % (name, key)
        transforms[did] = {"type": "dedupe", "inputs": [prev_id], "fields": {"match": [dedupe_key]}}
        prev_id = did

    vrl = ['.source = "capability"', '.device = "%s"' % key]
    vrl += list(method.get("transform_vrl") or [])      # the method's data-driven derivation, BEFORE the defaults
    # The canonical-field FALLBACKS, as an INFALLIBLE `if !is_string` guard (NOT `string(x) ?? default`): when a
    # method's transform_vrl PROVABLY assigns a string (e.g. `.level = if … {"info"} else {"error"}`), the compiler
    # proves `string(.level)` can't fail and Vector REJECTS the now-unnecessary `??` (VRL E651) — dogfood-caught on
    # proxmox_api. The guard form is identical in effect (keep a string value, else default) but never coalesces,
    # so it compiles whether the field is provably-string or maybe-null. Generic floor; a method derives the real
    # value upstream in transform_vrl.
    vrl.append('if !is_string(.service) { .service = "%s" }' % name)
    vrl.append('if !is_string(.host) { .host = "%s" }' % first_host)
    if "level" in (method.get("labels") or []):
        vrl.append('if !is_string(.level) { .level = "info" }')
    transforms[tid] = {"type": "remap", "inputs": [prev_id], "source": "\n".join(vrl) + "\n"}
    return tid, {"sources": {sid: src}, "transforms": transforms}


def logging_files(fleet, inv, methods=None, instance_trust=None):
    """-> {repo_rel_path: rendered_body} for every enabled module's `logs:` entries + the aggregate loki sink.
    Fail-closed: missing/unknown method, a param outside the allow-list, or a non-canonical label -> sys.exit.
    One fragment per (method, key) + ONE generated capability sink consuming all generated transforms.
    `instance_trust` is the optional `device_trust` map from instance.yml (per-class CA pins) the class-TLS
    resolution consumes (the no-bespoke vendor-fact ⊕ instance-decision seam)."""
    methods = methods or {m["name"]: m for m in catalog.load_logging()}
    instance_trust = instance_trust or {}
    out = {}
    transform_ids = []
    for key in fleet.get("enabled_modules") or []:
        mp = "modules/%s/module.yml" % key
        if not os.path.exists(os.path.join(ROOT, mp)):
            continue
        module = _load(mp)
        group = module.get("inventory_group")
        hosts = _hosts_in_group(inv, group)
        vendor_defaults = module.get("vendor_defaults")
        seen = set()
        for entry in (module.get("logs") or []):
            name = entry.get("method")
            if not name:
                sys.exit("gen-logging: %s has a logs entry with no 'method'" % key)
            method = methods.get(name)
            if method is None:
                sys.exit("gen-logging: %s references unknown logging method %r (add logging/%s.yml)"
                         % (key, name, name))
            _validate_params_or_exit(method, entry.get("params"), key)
            _validate_labels_or_exit(method, key)
            _validate_transform_vrl_or_exit(method, key)
            _validate_pull_shape_or_exit(method, key)
            _validate_credentialed_source_or_exit(method, key)
            rel = "%s/%s_%s.generated.yaml" % (GEN_DIR, name, key)
            if rel in seen:
                sys.exit("gen-logging: %s declares two logs entries for method %r" % (key, name))
            seen.add(rel)
            tid, frag = _render_fragment(method, key, group, hosts,
                                         vendor_defaults=vendor_defaults,
                                         instance_trust=instance_trust.get(key))
            transform_ids.append(tid)
            out[rel] = HEADER + yaml.safe_dump(frag, sort_keys=False, default_flow_style=False)
    if transform_ids:
        # the single aggregate sink: every generated transform -> Loki, with the canonical capability labels.
        sink = {"sinks": {"loki_capability": {
            "type": "loki", "inputs": sorted(transform_ids), "endpoint": "http://loki:3100",
            "encoding": {"codec": "json"}, "compression": "snappy", "out_of_order_action": "accept",
            "labels": {"source": "capability", "host": "{{ host }}", "service": "{{ service }}",
                       "level": "{{ level }}", "device": "{{ device }}"}}}}
        out["%s/_capability_sink.generated.yaml" % GEN_DIR] = (
            HEADER + yaml.safe_dump(sink, sort_keys=False, default_flow_style=False))
    return out


def _static_baseline_streams():
    """The static `limits_config.retention_stream` from loki-config.yml (the debug/audit baseline). Carried
    forward into any generated per-tenant override because a per-tenant retention_stream REPLACES (not merges)
    the static list for that tenant — dropping the baseline would silently regress the 90d audit retention to
    the 30d global (a C12 data-loss). Single-source: READ the committed config, never duplicate it. A drift-pin
    test holds the carried baseline == the static config."""
    cfg = _load(LOKI_CONFIG_REL)
    return list(((cfg.get("limits_config") or {}).get("retention_stream")) or [])


def loki_retention_files(fleet):
    """-> {LOKI_OVERRIDES_REL: body}: the generated Loki runtime_config OVERRIDES file enacting the per-class
    `retention` method param. Collect each enabled module's logs entries that set `retention`, map the preset to
    hours (>= 24h — M-1 F4), and emit `overrides.<tenant>.retention_stream` = the carried static baseline + one
    `{source="capability", device="<key>"}` entry per class (priority 10 — above the static debug(1)/audit(2)
    tiers, so a capability-specific window wins). FAIL-CLOSED: no class sets retention => `overrides: {}` (the
    stream inherits the bounded global LOKI_RETENTION_PERIOD — never empty=infinite). The file is ALWAYS valid
    YAML with only allow-list (>= 24h) periods, because an invalid runtime_config is FATAL at Loki startup (F4).
    A class that sets retention inconsistently across its logs entries exits non-zero (one device label => one
    window)."""
    per_key = {}
    for key in fleet.get("enabled_modules") or []:
        mp = "modules/%s/module.yml" % key
        if not os.path.exists(os.path.join(ROOT, mp)):
            continue
        for entry in (_load(mp).get("logs") or []):
            preset = (entry.get("params") or {}).get("retention")
            if preset is None:
                continue
            if preset not in _RETENTION_PRESET_HOURS:          # defence-in-depth (the method allow-list also gates)
                sys.exit("gen-logging: %s retention %r is not a known preset %s"
                         % (key, preset, sorted(_RETENTION_PRESET_HOURS)))
            if key in per_key and per_key[key] != preset:
                sys.exit("gen-logging: %s sets conflicting retention %r and %r across its logs entries "
                         "(one device label => one retention window)" % (key, per_key[key], preset))
            per_key[key] = preset
    if per_key:
        cap = [{"selector": '{source="capability", device="%s"}' % key, "priority": 10,
                "period": _RETENTION_PRESET_HOURS[per_key[key]]} for key in sorted(per_key)]
        body = {"overrides": {LOKI_TENANT: {"retention_stream": _static_baseline_streams() + cap}}}
    else:
        body = {"overrides": {}}
    return {LOKI_OVERRIDES_REL: LOKI_OVERRIDES_HEADER
            + yaml.safe_dump(body, sort_keys=False, default_flow_style=False)}


def main(argv):
    # The committed docker/vector/generated/*.yaml are the PUBLIC, example-derived reference (F3): `--check`
    # VALIDATES them and `--example` REGENERATES them from instance.example/ (TEST-NET addrs only). The bare write
    # (deploy-stack, live) reads the instance OVERLAY, so a running node regenerates its REAL drop-ins locally —
    # instance state, never committed to origin. (After a `logs:` edit, re-run `--example` for the committed lockfile.)
    if "--check" in argv or "--example" in argv:
        fleet = _load("instance.example/fleet.yml")
        inv = inventory.merged_inventory("instance.example/inventory/hosts.yml")
        instance_trust = _load_optional("instance.example/instance.yml").get("device_trust") or {}
    else:
        fleet = _load(paths.resolve("config/fleet.yml"))
        inv = inventory.merged_inventory(paths.resolve("ansible/inventory/hosts.yml"))
        # OPTIONAL per-class trust DECISIONS (instance data) — `device_trust.<key>.tls_ca_file` pins a CA; absent
        # => the class vendor default posture. Read from the instance overlay (absent on a fresh node => no pins).
        instance_trust = _load_optional("instance/instance.yml").get("device_trust") or {}
    want = {os.path.normpath(os.path.join(ROOT, rel)): body
            for rel, body in dict(logging_files(fleet, inv, instance_trust=instance_trust),
                                  **loki_retention_files(fleet)).items()}
    have = {os.path.normpath(p)
            for d in (GEN_DIR, os.path.dirname(LOKI_OVERRIDES_REL))
            for p in glob.glob(os.path.join(ROOT, d, "*.generated.yaml"))}

    if "--check" in argv:
        stale = []
        for path, body in want.items():
            cur = open(path, encoding="utf-8").read() if os.path.exists(path) else None
            if cur != body:
                stale.append(os.path.relpath(path, ROOT))
        for path in have - set(want):
            stale.append(os.path.relpath(path, ROOT) + " (orphaned)")
        if stale:
            print("STALE Vector logging drop-ins — re-run scripts/gen-logging.py --example:\n  " + "\n  ".join(stale))
            return 1
        print("Vector logging drop-ins up to date (%d file(s))" % len(want))
        return 0

    for d in (GEN_DIR, os.path.dirname(LOKI_OVERRIDES_REL)):
        os.makedirs(os.path.join(ROOT, d), exist_ok=True)
    for path in have - set(want):                # prune orphans first (a removed module/host)
        os.remove(path)
    for path, body in want.items():
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(body)
    print("wrote %d logging drop-in(s): %s"
          % (len(want), ", ".join(sorted(os.path.relpath(p, ROOT) for p in want)) or "(none)"))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
