#!/usr/bin/env bash
# host-systemd.sh — the small HOST-systemd residual the compose-native install can't put in a container.
#
# WHY a residual: the installer runs in an EPHEMERAL container with no systemd, so the few genuinely host-level,
# systemd-managed concerns can't live there (synthesis §4.5 / MF-5). Today that is exactly qemu-guest-agent (the
# Proxmox guest integration — clean shutdown, IP reporting), which bootstrap.yml used to install + enable and now
# skips when `KONTROLL_IN_CONTAINER=1`. journald-remote + logrotate are reserved here for the logging Layer-0
# host pieces (docs/logging-architecture.md) — wire them when those land; they are intentionally inert stubs now.
#
# Idempotent: every step is a no-op on a node that already has it. OPTIONAL — the stack runs without it; it just
# improves Proxmox guest integration. Run AFTER install-prereqs.sh.
#
# Usage:  sudo bash scripts/host-systemd.sh
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "host-systemd.sh needs root (it installs a package + manages a systemd unit). Re-run: sudo bash $0" >&2
  exit 1
fi

# Package-manager dispatch (nixflavor-agnostic), shared with install-prereqs.sh. The systemd gating below is
# already init-system-aware; this makes the package INSTALL flavor-agnostic too (scripts/lib/pkg.sh).
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=scripts/lib/pkg.sh
. "$SCRIPT_DIR/lib/pkg.sh"
PKG_MGR="$(pkg_detect)"
if [ "$PKG_MGR" = unknown ]; then
  echo "host-systemd.sh: no supported package manager (apt/dnf/zypper/pacman) — this OPTIONAL script does nothing." >&2
  echo "Install qemu-guest-agent + logrotate for your distro by hand if you want Proxmox integration + the G5 cap." >&2
  exit 0
fi

export DEBIAN_FRONTEND=noninteractive
[ "$PKG_MGR" = apt ] && echo 'DPkg::Lock::Timeout "600";' > /etc/apt/apt.conf.d/99kontroll-lock-timeout

echo "==> qemu-guest-agent (Proxmox guest integration)…"
pkg_refresh
pkg_install qemu-guest-agent
# `systemctl enable --now` is the idempotent equivalent of bootstrap's old `systemd: enabled+started`. Tolerate a
# non-systemd / non-Proxmox host (e.g. a bare-metal control node) without aborting the script.
if systemctl list-unit-files qemu-guest-agent.service >/dev/null 2>&1; then
  systemctl enable --now qemu-guest-agent >/dev/null 2>&1 \
    && echo "    qemu-guest-agent enabled + started." \
    || echo "    qemu-guest-agent present but not started (no virtio-serial? not a Proxmox guest — harmless)."
else
  echo "    qemu-guest-agent unit not found (not a systemd host? — skipping enable)."
fi

# logrotate for the ansible run-log (G5). deploy-stack used to do this, but the drop-in must land on the HOST (a
# drop-in written inside the ephemeral installer container never reaches the host's logrotate), so it moves here.
# Bounds {storage_root}/ansible-log/*.log; copytruncate keeps the inode Vector tails by exact path. Defaults match
# deploy-stack (5M x 5). Override KONTROLL_ANSIBLE_LOG_DIR if you relocated the storage root.
ANSIBLE_LOG_DIR="${KONTROLL_ANSIBLE_LOG_DIR:-/var/lib/kontroll/ansible-log}"
echo "==> logrotate + the ansible-run-log drop-in (G5) for ${ANSIBLE_LOG_DIR}…"
pkg_install logrotate
cat > /etc/logrotate.d/kontroll-ansible-log <<LOGROTATE
# GENERATED by scripts/host-systemd.sh — bounds the kontroll ansible run-log (G5).
${ANSIBLE_LOG_DIR}/*.log {
    size ${KONTROLL_ANSIBLE_LOG_MAX_MB:-5}M
    rotate ${KONTROLL_ANSIBLE_LOG_MAX_FILES:-5}
    missingok
    notifempty
    copytruncate
    compress
    delaycompress
}
LOGROTATE
chmod 0644 /etc/logrotate.d/kontroll-ansible-log

# --- Reserved host-systemd residual (logging Layer 0) — intentionally inert until that feature lands -----------
# journald-remote : a systemd-journal-remote receiver for device syslog → journald (docs/logging-architecture.md).
# Wire here (NOT in the installer container) when built; keeping the residual in ONE host script avoids scattering
# host-only systemd steps back into the playbooks the installer runs.

echo "==> Host-systemd residual done (idempotent)."
