"""bootstrap.yml must resolve the collection set through the SINGLE-SOURCE generator, never a hand-maintained
inline copy.

WHY (the failure this guards): bootstrap.yml used to carry its OWN inline Jinja requirements-merge — seed from
modules/_core.yml, loop-merge each enabled module's `collections`, then render
ansible/collections/requirements.generated.yml from an `all_collections` fact. That duplicated
scripts/gen-requirements.py (which deploy-stack.yml and CI already call) — the "two-derivation-path divergence
hazard": a change to the resolution/dedup logic in one place silently diverged from the other, so the runner image
could bake a different collection set than CI validated. R0 of the GUI-actuation build collapsed bootstrap onto
gen-requirements.py (see docs/reviews/2026-06-24-gui-actuation-design/, F4). These pins keep the collapse from
regressing: the generator call must exist and precede the install, and the inline `all_collections` resolution must
stay gone.
"""
import os

import pytest

pytestmark = pytest.mark.unit

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BOOTSTRAP = os.path.join(ROOT, "ansible", "playbooks", "bootstrap.yml")


def _src():
    with open(BOOTSTRAP, encoding="utf-8") as fh:
        return fh.read()


def test_bootstrap_resolves_collections_via_single_source_generator():
    """bootstrap.yml MUST call scripts/gen-requirements.py (the one resolver deploy-stack + CI use) and that call
    MUST precede the install — the install reads the lockfile + trust sidecar the generator writes. The install
    step is now the never-brick wrapper (scripts/install-collections.py, C15-a), not the raw `ansible-galaxy`."""
    src = _src()
    gen = src.find("gen-requirements.py")
    install = src.find("install-collections.py")
    assert gen != -1, "bootstrap must regenerate the lockfile via the single-source scripts/gen-requirements.py"
    assert install != -1, "bootstrap must install via the never-brick wrapper scripts/install-collections.py"
    assert gen < install, "the lockfile + sidecar must be generated BEFORE the collections are installed from them"


def test_bootstrap_install_goes_through_the_never_brick_wrapper():
    """The install MUST run through scripts/install-collections.py (the adaptive-signature, pin+checksum-floor
    wrapper) — NOT a raw `ansible-galaxy collection install`, which has no signature posture. Guards a regression
    that drops the never-brick install behaviour (C15-a) back to an unverified flat install."""
    src = _src()
    assert "install-collections.py" in src, "bootstrap must install via the never-brick wrapper"
    assert "ansible-galaxy collection install" not in src, (
        "the raw flat install must be gone — the never-brick posture lives in scripts/install-collections.py"
    )


def test_bootstrap_does_not_reintroduce_an_inline_collection_resolution():
    """The collapse removed bootstrap's duplicate resolution. Pin it gone: no `all_collections` fact and no inline
    Jinja render of the lockfile (the `{% for c ... %}` body / the old bootstrap-authored GENERATED header). Their
    return would re-open the divergence hazard this commit closed."""
    src = _src()
    assert "all_collections" not in src, (
        "bootstrap must not recompute the collection set inline — resolution belongs only to gen-requirements.py"
    )
    assert "GENERATED by playbooks/bootstrap.yml" not in src, (
        "bootstrap must not hand-render requirements.generated.yml — gen-requirements.py owns the lockfile content"
    )
